### ISSUE TITLE
功能：主题定制

### ISSUE THREAD

**Issue by liujinxing** [sinoui/sino-intellisense-form#102]
* [x] 表单设计器、流程设计器的背景色
* [x] 表单设计器、流程设计器的字体颜色、大小

**Comment by maitian0222** [comment]
1.表单设计器中字段选中的背景色、鼠标悬浮颜色等涉及到颜色的地方修改为当前主题色（blue）
2.流储能设计器中节点、路由等涉及到颜色的地方修改为当前主题色（blue）

**Comment by fulimin123** [comment]
表单制作页面，发现一些背景色不是蓝色的，我这边不清楚你们是特意保留的还是忘记修改了，上传图片，你们酌情处理下。
![地址选择背景色，未调成蓝色](https://user-images.githubusercontent.com/59549153/74399432-c4d98d80-4e55-11ea-9821-513bbecae6b5.png)
![节点：流转规则，背景未调成蓝色](https://user-images.githubusercontent.com/59549153/74399436-c905ab00-4e55-11ea-9f7d-67cea5a4ec4c.png)
![节点：文本意见背景，未调成蓝色](https://user-images.githubusercontent.com/59549153/74399438-cc993200-4e55-11ea-911e-dcdbdaada866.png)
![路由：本门级别，背景未调成蓝色](https://user-images.githubusercontent.com/59549153/74399444-cefb8c00-4e55-11ea-8b60-5ad89c5e21de.png)
![下拉选项背景色未调成蓝色](https://user-images.githubusercontent.com/59549153/74399448-d15de600-4e55-11ea-981c-e9b996f966d3.png)
![选中的人员背景色，未调成蓝色](https://user-images.githubusercontent.com/59549153/74399449-d3c04000-4e55-11ea-83af-3310341eeb60.png)
![背景色](https://user-images.githubusercontent.com/59549153/74399452-d58a0380-4e55-11ea-8a72-b09ec9152fc1.png)
![1](https://user-images.githubusercontent.com/59549153/74399468-e3d81f80-4e55-11ea-9ca8-84dfbb435958.png)

**Comment by liujinxing** [comment]
@fulimin123 你反馈的不用处理。这是设计中 Select 组件默认的设定。

**Comment by fulimin123** [comment]
开发反馈：保持当前背景样式，不需要进行处理

**Comment by liujinxing** [comment]
@fulimin123 有新的设计标准。会采用新的设计标准来处理下拉框选中颜色。

**Comment by maitian0222** [comment]
@fulimin123 表单发布页面提示语的背景色保持当前不变。

**Comment by maitian0222** [comment]
@fulimin123 下拉框选中颜色修改为主题色

**Comment by fulimin123** [comment]
1.预览中，下拉选择、地址选择下拉框的背景颜色未调整
2.流程设计中授权位置的背景颜色未调整。
3.流程设计中，流转规则背景未调整。
建议开发人员细节方面再逐一点击一下进行排查。

**Comment by fulimin123** [comment]
设计样式：选中项才会应用主题色。

**Comment by liujinxing** [comment]
@fulimin123 下拉框的设计是这样的：

## 未选中，但是获取到焦点的情况，使用灰色背景

![image](https://user-images.githubusercontent.com/1055306/75084032-487f3280-5558-11ea-9aab-7e650f504408.png)

这种情况是没有选中项的：

![image](https://user-images.githubusercontent.com/1055306/75084053-6b114b80-5558-11ea-817b-d89ed75fe9de.png)

## 选中项，使用主题色

![image](https://user-images.githubusercontent.com/1055306/75084062-811f0c00-5558-11ea-9303-d783947f6165.png)

![image](https://user-images.githubusercontent.com/1055306/75084066-8714ed00-5558-11ea-920e-f52cfb2c4f51.png)
