### ISSUE TITLE
特性：意见增加常用意见

### ISSUE THREAD

**Issue by maitian0222** [sinoui/sino-intellisense-form#129]
1.在数据填报页面的填写意见区域处增加常用意见和保存意见常用意见按钮
2.用户只能获取自己保存的常用意见

**Comment by fulimin123** [comment]
添加常用意见功能没有问题，当前存在的问题是，添加完了删除不了，没有删除的功能。

**Comment by fulimin123** [comment]
目前，添加的常用意见仍删除不了，这个问题是处理还是就这样呢？

**Comment by maitian0222** [comment]
@fulimin123 常用意见暂时不做删除功能。

**Comment by fulimin123** [comment]
pass
