### ISSUE TITLE
把单行文本设置为标题项后，在草稿列表页面，系统把多行文本中输入的内容也作为标题的一部分了。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#148]
步骤：1.在表单设置中添加单行文本，设置为待办标题；
          2.在单行文本下添加多行文本，选择为非待办标题。
          3.再添加其他字段发布，审核通过，使用用户登录起草列表，输入完必填项保存后，在草稿列表中可看到标题中显示了单行文本和多行文本中输入的内容。
![问题附件](https://user-images.githubusercontent.com/59549153/71817604-4f91d480-30c1-11ea-9c92-0c030e998d33.png)

**Comment by maitian0222** [comment]
草稿列表中，第一行中没有label名称的是标题，其余文字都是表单其他字段内容。草稿列表默认显示前5个可以在列表中显示的字段。
![image](https://user-images.githubusercontent.com/20694684/71859920-a7652580-312b-11ea-9a60-10518fe28250.png)
