### ISSUE TITLE
文本类型选择“数字”，预览时，未校验文本类型，可输入字母、汉字、特殊符号

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#155]
现象：文本类型选择“数字”，预览时，未校验文本类型，可输入字母、汉字、特殊符号
预期：当文本类型选择数字时，建议校验可输入类型为数字，其他类型不允许输入。
![问题附件1](https://user-images.githubusercontent.com/59549153/71864638-49403e80-313b-11ea-89cb-2e51e8c5c03e.png)
注：在火狐器中出现的该问题，谷歌浏览器不存在这个问题。

**Comment by tianyanqiu** [comment]
此问题由于<input type="number"/>在IE和Firfox浏览器并不兼容导致，在IE浏览器输入完成时，如果不是数字，会自动清空;firfox浏览器则会显示在页面，但是读取到的值为undefined。此问题打算放入新的@sinoui/core/TextInput中统一处理，需要商讨解决方案 @liujinxing

**Comment by liujinxing** [comment]
@tianyanqiu 建议在 number-input 模块中处理。对于 IE 和 Firefox，将 type 仍然设置为 "text"，而不是 "number"，然后控制其输入的字符，并在最后检验数字的有效性。

**Comment by fulimin123** [comment]
pass

**Comment by fulimin123** [comment]
火狐和ie11都做了校验。
