### ISSUE TITLE
单行文本，当数据格式选择身份证号时，应用后，未校验身份证号的有效性

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#156]
现象：1.表单设计中，单行文本，数据格式选择省份证号
          2.在预览页面，任一输入15位或18位数字，但是不符合身份证号规则时，可检验通过
建议：校验15位和18位身份证号的有效性。

**Comment by maitian0222** [comment]
修改后输入身份证后会验证18位身份证号出生月份和出生日期是否满足条件。但前6位的地区代码除了六个0以外，只要是数字都认为是有效的。

**Comment by fulimin123** [comment]
测试通过
