### ISSUE TITLE
表单设计中，日期时间选择年-月-日-时:分:秒，应用后，时分秒显示不出来

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#163]
现象：1.表单设计中，日期时间选择年-月-日-时:分:秒，应用后，显示的是年-月-日，而时分秒并未显示。
           2.表单设计中，日期时间选择年-月，应用后，显示的是年-月-日
![问题附件](https://user-images.githubusercontent.com/59549153/71877427-1494ad00-3164-11ea-8d91-cab46a85336d.png)

**Comment by liujinxing** [comment]
暂时不支持时分秒。可以将日期时间选择屏蔽掉。

**Comment by fulimin123** [comment]
测试通过
