### ISSUE TITLE
表单设计中，部门选择范围选择本部门，应用后，部门选择范围和起草用户所在部门不符

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#165]
现象：在表单设计中，部门选择范围选择了“本部门”，应用后，汪芳登录起草，汪芳是公文处人员，但是部门选择中未显示公文处。见附件
![1-1](https://user-images.githubusercontent.com/59549153/71878665-2592ed80-3167-11ea-9923-eb468bf3f553.png)
![1-2](https://user-images.githubusercontent.com/59549153/71878671-2a57a180-3167-11ea-854d-dbda521b8d95.png)
![1-3](https://user-images.githubusercontent.com/59549153/71878679-2deb2880-3167-11ea-958b-94236f0b1a6d.png)

**Comment by liujinxing** [comment]
在树中，也将公文处作为顶级节点显示出来。

**Comment by maitian0222** [comment]
需要后端接口返回父级部门

**Comment by fulimin123** [comment]
该问题仍存在

**Comment by fulimin123** [comment]
测试通过
