### ISSUE TITLE
表单设计中，下拉选项和用户选择都为多选，应用后，下拉选项字段会覆盖后面字段；

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#167]
现象：
1.表单设计中，下拉选项为多选，1/3布局，应用后，回写的选项会覆盖后面的字段。
2.用户选择选择类型为多选，1/3布局，应用后，存在用户名显示不全、不满一行就换行的情况。
![问题附件-a](https://user-images.githubusercontent.com/59549153/71879726-b8348c00-3169-11ea-89f8-88d037f61134.png)

**Comment by liujinxing** [comment]
应该是文本断行没有对英文字符做特殊处理。

**Comment by fulimin123** [comment]
回测情况：1中的问题仍存在。
当下拉选项中的可选项字数较多时或选择了多个选项时，回写后都会把后面的字段遮盖上。此处采用1/4活儿1/3布局

**Comment by tianyanqiu** [comment]
1中的问题由于代码未更新依赖包导致，已重新部署，可回测。

**Comment by fulimin123** [comment]
测试通过
