### ISSUE TITLE
部门选择、用户选择允许上传多个时，会覆盖和占用下一行的字段；附件上传后显示异常。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#173]
现象：
在子表单中：
1.部门选择、用户选择允许上传多个时，会覆盖和占用下一行的字段
2.附件上传后样式难看、且总数只能显示4个，上传超过4个显示不了，无论是哪行上传的附件，总数中只能显示4个，其它会自动溢出到显示窗口外。
![a](https://user-images.githubusercontent.com/59549153/71945694-7572c280-3202-11ea-8e57-182690c08b63.png)

**Comment by tianyanqiu** [comment]
附件上传将禁止在子表单中使用

**Comment by fulimin123** [comment]
测试通过
