### ISSUE TITLE
流程设计中，路由路径，是否跨部门为否，应用后发送时，显示出的选项跨部门了。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#176]
1.现象：起草节点的路由为不跨部门，起草完发送后，可选到其他部门的处长。
![a-1](https://user-images.githubusercontent.com/59549153/71958138-7d465d00-322a-11ea-9511-a19e5e0c62c2.png)
![a-2](https://user-images.githubusercontent.com/59549153/71958156-8a634c00-322a-11ea-8c4d-be257610e7f0.png)
![a-3](https://user-images.githubusercontent.com/59549153/71958183-99e29500-322a-11ea-815b-b41e992c2b66.png)

**Comment by wxz0107** [comment]
此处 跨部门为否的时候，是直属部门的概念 并非同部门的概念
直属同级就是后继节点的参与者和前驱节点的参与者父部门是相同的。此处汪芳属于（公文处/金融保险部）。所以直属同级 指的是金融保险部下级部门的人员。下一个节点指向的是处长
![image](https://user-images.githubusercontent.com/8895642/72231510-d5001200-35f6-11ea-912a-ab0d4f057463.png)
符合条件的就是前4个 和路由给出的结果相同

**Comment by liujinxing** [comment]
@wxz0107 现在有同部门的概念么？

**Comment by liujinxing** [comment]
按照需求设定，跨部门选择否，即是同部门的概念。在实际应用中，同部门的用处更大。直属部门很容易由跨部门 + 部门范围实现，而同部门就没有替代方案。 @wxz0107

**Comment by liujinxing** [comment]
举一个场景，科员要将流程送到自己的处长，处长要将流程送到自己的司长，司长要将流程送到自己的局长。

**Comment by liujinxing** [comment]
另一个场景：处长要将流程发给自己部门下的科长。

**Comment by liujinxing** [comment]
“路由设计范围”新增一个“同部门”选项，并去掉备受歧义的“同级”选项。“同部门”选项不受“是否跨部门”影响。
