### ISSUE TITLE
盖完章后，点击“退回”或“退回起草人”按钮后，被退回节点或拟稿人节点打开待办，所盖的公章并未消失。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#182]
现象：当前系统盖章功能，盖完章后，公章删除不了。
实际业务中是否有删除公章的需要（例如，盖完章后又想退回了，但是章删除不了），若有，建议增加删除公章的功能。

**Comment by liujinxing** [comment]
是谁盖的章，谁拥有权限删除章。另外，表单发生变化了，章也会自动消失，这是规则是为了确保章的有效性。

**Comment by fulimin123** [comment]
我有个疑问，我用陈振林盖章后，没有找到可删除章的地方。

**Comment by maitian0222** [comment]
先点击公章图片，然后使用Delete键删除。若没有删除权限，会显示提示语。

**Comment by fulimin123** [comment]
经测试当前系统情况为：
1.盖完章后，点击“退回”或“退回起草人”按钮后，被退回节点或拟稿人节点打开待办，所盖的公章并未消失。
![a-a](https://user-images.githubusercontent.com/59549153/72036541-167e7d80-32d6-11ea-90da-cb1b14e2444c.png)

**Comment by liujinxing** [comment]
暂时不采纳“退回”、“退回起草人”自动删除章规则。
