### ISSUE TITLE
bug:功能缺失及不规范的操作

### ISSUE THREAD

**Issue by tianyanqiu** [sinoui/sino-intellisense-form#19]
- [x] 新建表单返回时，应该支持用户选择是否保存而非强制保存。
- [x] 表单设计器：表单列表需要支持删除
- [ ] ~~表单设计器：表单的复制~~
- [x] 草稿列表缺少删除按钮
- [x] 查看草稿缺少流程操作按钮
- [x] 子表单字段设置为只读状态时，表单详情页的子表单字段操作按钮需要设置为禁用状态或不显示操作按钮
- [x] 高级搜索点击查询后，查询项值不应该被清空

**Comment by liujinxing** [comment]
表单设计的样式调整：阴影

![image](https://user-images.githubusercontent.com/1055306/69840088-45e0aa00-1295-11ea-8328-50eaa2e36975.png)

希望达到的效果：

![image](https://user-images.githubusercontent.com/1055306/69840111-5b55d400-1295-11ea-8b07-b329a5653759.png)

**Comment by liujinxing** [comment]
* [ ] 表单设计的中间区域背景色设置为白色

![image](https://user-images.githubusercontent.com/1055306/69840223-b5ef3000-1295-11ea-8ccd-ab9d9f40198b.png)

**Comment by liujinxing** [comment]
* [ ] 地址选择不允许拖拽到子表单中

![image](https://user-images.githubusercontent.com/1055306/69840412-678e6100-1296-11ea-8d15-109c5be63497.png)

**Comment by liujinxing** [comment]
* [ ] 缺陷：新建表单时，如果不修改标题，直接点击保存，保存失败，没有创建新的表单，而是出现一个id 为空的未命名表单。

![image](https://user-images.githubusercontent.com/1055306/69840930-3151e100-1298-11ea-82c9-7d1481ae1f9a.png)

**Comment by liujinxing** [comment]
* [ ] 缺陷：新建表单时，直接修改标题，自动保存标题后，标题被置空，且 url 中的 id 变成 undefined

新建：

![image](https://user-images.githubusercontent.com/1055306/69841015-8c83d380-1298-11ea-9f02-7c5074b1c6b4.png)

自动保存标题后：

![image](https://user-images.githubusercontent.com/1055306/69841061-c81e9d80-1298-11ea-9bfe-4f913dc5ce76.png)

**Comment by liujinxing** [comment]
* [ ] 地址选择优化：添加提示语

类似如：

![image](https://user-images.githubusercontent.com/1055306/69844219-2605b200-12a6-11ea-8abd-c5f414c688ab.png)
