### ISSUE TITLE
起草人发送后，立即在已办列表中，点击收回按钮，收回失败

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#192]
![a](https://user-images.githubusercontent.com/59549153/72045529-4424f000-32f1-11ea-954d-6eb1d27c2d87.png)

**Comment by liujinxing** [comment]
和“所有负责人提交后进入下一节点”这个规则有关。

**Comment by wxz0107** [comment]
如果是同时办，不支持主动收回

**Comment by fulimin123** [comment]
重新建表单，流转规则选择：所有负责人提交后进入下一节点，发布，审核通过后，起草人起草完，点击收回按钮，仍提示收回失败。

**Comment by liujinxing** [comment]
@fulimin123 这种情况下，支持不了 “收回” 操作。正在安排做屏蔽操作。

@wxz0107 这种情况下，做一下 “收回” 的屏蔽操作。

**Comment by wxz0107** [comment]
今天昨天的分析和测试 发现 同时办也是可以主动收回的。之前的错误是应该工作流报错导致的。现在已经修复。麻烦重新测试一下
![image](https://user-images.githubusercontent.com/8895642/72396408-89c13d00-3777-11ea-93d2-630b1d67cf1b.png)

**Comment by fulimin123** [comment]
测试通过
