### ISSUE TITLE
已办列表中按时间查询时结果不准确；按字段排序有问题；未显示办理总数

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#195]
![a](https://user-images.githubusercontent.com/59549153/72050267-ae429280-32fb-11ea-8a64-3af1ce9d4933.png)

**Comment by fulimin123** [comment]
问题2和问题3同时存在于待办列表中。

**Comment by fulimin123** [comment]
回测情况：
问题1：测试通过；
问题2：当前系统中去掉了各个字段的排序功能；这个功能是否保留？
问题3：统计总数的功能并未加上；建议加上

**Comment by maitian0222** [comment]
问题2：之后会实现全部数据排序功能，当前版本暂不实现排序功能
问题3：统计总数已增加 显示为
![image](https://user-images.githubusercontent.com/20694684/72244789-f7f7e980-3629-11ea-9328-6c538b9acea2.png)

**Comment by fulimin123** [comment]
pass
