### ISSUE TITLE
查询列表排序存在问题。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#197]
现象：1.按照系统默认字段显示，分别点击表头字段排序，能排除三种顺序来；
              预期：只有正序和倒序两种排列方式。
现象：2.排序时也存在只排当期页的情况，后面的数据不被排序。
             预期：按照所有数据进行排序。
![0000](https://user-images.githubusercontent.com/59549153/72051082-7e948a00-32fd-11ea-9e16-65dcff8c9be6.png)

**Comment by liujinxing** [comment]
如果不支持排序，直接屏蔽掉排序。

**Comment by liujinxing** [comment]
@fulimin123 排序功能未实现，已屏蔽。

**Comment by fulimin123** [comment]
通过
