### ISSUE TITLE
查询列表，高级搜索，保存为常用搜索后，再删除时删除不了

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#198]
![0000](https://user-images.githubusercontent.com/59549153/72053767-a4705d80-3302-11ea-9226-449b589b5251.png)

**Comment by liujinxing** [comment]
@fulimin123 之前创建的查询条件不能再删除了，需要创建新的查询条件才能删除。

**Comment by fulimin123** [comment]
pass
