### ISSUE TITLE
自定义选择下拉选择，该字段页面中的数据未被带出。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#204]
查询列表：
自定义选择下拉选择，该字段页面中的数据未被带出。
![0000](https://user-images.githubusercontent.com/59549153/72061017-01264500-3310-11ea-94c1-c05dc2f3092e.png)

**Comment by liujinxing** [comment]
@fulimin123 需要使用新数据才能验证。

**Comment by fulimin123** [comment]
测试通过
