### ISSUE TITLE
流程审批属性设置为允许内部流转，起草人发送时选择送处长审核（内部流转），弹出的可选择部门把其他司下的处级也显示了出来。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#208]
![image](https://user-images.githubusercontent.com/59549153/72067555-f2df2580-331d-11ea-8f66-38446550679d.png)

**Comment by wxz0107** [comment]
跨部门是否时的含义是直属部门

**Comment by liujinxing** [comment]
与 #176 一个类型的问题。
