### ISSUE TITLE
设计时”允许内部流转“是”，是否跨部门“否”“应用后，内部流转时，把其他部门及其人员也显示了出来

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#211]
问题：设计时”允许内部流转“是”，是否跨部门“否”“应用后，内部流转时，把其他部门及其人员也显示了出来
预期：内部流转时，只显示部门内符合条件的人员。
![图0](https://user-images.githubusercontent.com/59549153/72119540-b9df9900-338f-11ea-8da2-56a2fec9f028.png)
![图1](https://user-images.githubusercontent.com/59549153/72119552-c532c480-338f-11ea-84e1-7119337ef158.png)

**Comment by liujinxing** [comment]
同 #176 同一类问题。
