### ISSUE TITLE
流程设计的是“不允许内部流转”，应用后，出现了内部流转的选项

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#212]
![图0](https://user-images.githubusercontent.com/59549153/72120537-3e7fe680-3393-11ea-9b28-c3b35d6b37f4.png)
![图1](https://user-images.githubusercontent.com/59549153/72120547-463f8b00-3393-11ea-8325-ce726622b03a.png)

**Comment by wxz0107** [comment]
重新发布 重新审核 重新起业务单子 不是实时生效的

**Comment by wxz0107** [comment]
我自己测试了一遍 发现没有问题可以复测一下

**Comment by fulimin123** [comment]
测试通过
