### ISSUE TITLE
当办结节点不内部流转时，该节点发送按钮点击时给出提示。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#213]
在办结节点，如果用户没有设计内部流转的功能，应用后，直接点击发送时建议给出提示信息“是否办结”，确认后，再结束流程。
![现象](https://user-images.githubusercontent.com/59549153/72121898-58232d00-3397-11ea-8bde-bf1a34291eb8.png)

**Comment by fulimin123** [comment]
现在系统给出的提示是“是否发送”。预期：提示信息“是否办结”。
可看2-21-1E打印 ，这个表单。

**Comment by maitian0222** [comment]
@fulimin123 提示信息已改为“确定办结”。和其他按钮的提示信息“确定xx”保持一致。

**Comment by fulimin123** [comment]
pass
