### ISSUE TITLE
优化:表单设计中新增字段或删除字段后，流程节点的字段权限需要自动更新

### ISSUE THREAD

**Issue by maitian0222** [sinoui/sino-intellisense-form#215]
之前的实现是表单设计中新增字段后，需要在流程设计中的节点再点击更多属性设置才会在该节点击加上新增的字段。
现修改为新增或删除字段后，不需要打开流程设计器进行字段设置，保存后节点字段权限自动更新。

**Comment by maitian0222** [comment]
原来的实现是表单设计中新增字段后，需要在流程设计中的节点再点击更多属性设置才会在该节点击加上新增的字段。现修改为新增或删除字段后，不需要再打开流程设计器进行字段设置，保存后节点字段权限实现更新。

**Comment by fulimin123** [comment]
pass
