### ISSUE TITLE
用户进入系统后，不要默认显示草稿页面。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#216]
当前现象：用户进入系统后，直接就显示了草稿列表页面；
建议：不要直接显示草稿，可显示welcome那个页面。用户点击各子系统后再点什么显示什么即可。
原因：左侧子系统有些是没有起草权限的，有些有起草权限，但是用户怎么分辨这个草稿是哪个子系统的草稿呢？
![建议](https://user-images.githubusercontent.com/59549153/72123192-696e3880-339b-11ea-9df3-45c2b7859866.png)

**Comment by liujinxing** [comment]
这个 issue 暂时不处理。因为这是依赖的案例系统本身的问题。而且一般情况下不会出现这种问题。
