### ISSUE TITLE
各节点按成员授权，应用后，起草流程且结束，其上级领导查看不到该条数据

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#219]
步骤：
1.在流程设计中按照“成员”授权，只有科级（王帅）、处级（汪芳）两个节点。
2.起草流程，流程结束后，本处的处长和司长没有这个智能表单及查看列表，看不到起草的该流程。
![图1](https://user-images.githubusercontent.com/59549153/72134326-b7e0fe80-33be-11ea-8899-5e60354dc638.png)
![图2](https://user-images.githubusercontent.com/59549153/72134345-c5968400-33be-11ea-9f24-301beb6d86cf.png)

**Comment by fulimin123** [comment]
补充：
1.按照角色授权，起草流程，只有科级（科员）和处级（处员），流程结束后，本单位处长和司长也没有查看列表，看不到数据。
2.安组织架构授权，起草流程，只授权科级和处级，流程结束后，本单位司级领导看不到查看列表及数据。

**Comment by liujinxing** [comment]
@fulimin123 查询列表以下人员可见：

* 流程配置中的负责人（包括选择的部门、业务角色、人员）
* 在发布时选择的数据查看人员

只有符合这两种情况，才会在导航中看见查询列表。
