### ISSUE TITLE
子菜单是否输入内容，会影响是否能够弹出打印预览。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#226]
问题现象：
1.页面中子菜单不输入内容，点击打印，可成功输出。在子菜单中输入内容，再点击打印按钮，提示“打印输出失败”，无法打印；
2.附上中上传附件，打印后，预览中附件位置的附件没有被带出来。
注：测试时使用了flm这个表单，使用汪芳登录，在flm这个表单系统中起草，在子菜单中输入内容保存，看打印效果。
![子菜单](https://user-images.githubusercontent.com/59549153/72229669-52258a00-35eb-11ea-8f67-f562473a6d54.png)

**Comment by liujinxing** [comment]
@fulimin123 这个缺陷短期内无法直接解决，你需要按照下面的方式调整一下打印输出模板。

![image](https://user-images.githubusercontent.com/1055306/72230766-9f592a00-35f2-11ea-9660-99833acea2e3.png)

**Comment by fulimin123** [comment]
回测情况，模板中子菜单和附件调整正常位置应用后，去系统中重新起草，在处长节点查看“打印”按钮，此时可成功打开预览页面，但是子菜单的数据带出显示有问题；附件内容也未显示。
![子菜单和附件](https://user-images.githubusercontent.com/59549153/72232131-2362e000-35fa-11ea-8518-5e0e21cf28d5.png)

**Comment by fulimin123** [comment]
![12345](https://user-images.githubusercontent.com/59549153/72307505-7c437e80-36b5-11ea-8ea2-8c096708f65e.png)

**Comment by fulimin123** [comment]
pass
