### ISSUE TITLE
word模板上传应用后，流程中点击打印按钮，查看打印预览页面后单选按钮组、多选按钮组、下拉选项字段存在问题

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#227]
1.单选按钮组和多选按钮组，打印预览页面的排列顺序混乱。
2.下拉选择按钮，打印预览页面没有把该字段数据带不出来。
![打印页面问题](https://user-images.githubusercontent.com/59549153/72229729-d0822c00-35eb-11ea-914f-b9b48473be69.png)

**Comment by liujinxing** [comment]
@fulimin 使用新数据验证一下下拉选择框的打印输出。

**Comment by fulimin123** [comment]
测试通过
