### ISSUE TITLE
起草节点显示了文本意见框

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#228]
现象：在流程设计中，各个节点文本意见项设置为必填或选填应用后，     在开始节点，把填写意见的
           意见框显示出来了。
预期：起草节点不显示填写意见框。

**Comment by maitian0222** [comment]
因为判断写成了flowIdea?.idea !== 'disabled'的问题，因为flowIdea?.idea有可能为undedined。改为flowIdea?.idea && flowIdea?.idea !== 'disabled'就可以了。

**Comment by fulimin123** [comment]
测试通过
