### ISSUE TITLE
bug（智能表单后台管理）：打开表单设计页，点击回退图标之后点击不保存，退回的页面不正确

### ISSUE THREAD

**Issue by liujinxing** [sinoui/sino-intellisense-form#23]
点击不保存：

![image](https://user-images.githubusercontent.com/1055306/69844808-bd6c0480-12a8-11ea-961a-7fd8673ff1d4.png)

进入了空白页：

![image](https://user-images.githubusercontent.com/1055306/69844820-cbba2080-12a8-11ea-8496-0efc69a1b7b9.png)

**Comment by maitian0222** [comment]
已修改，路由地址已修改。需要更新代码
