### ISSUE TITLE
授权人员的名字没有显示完整

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#234]
![现象aa](https://user-images.githubusercontent.com/59549153/72258850-0ce47500-364a-11ea-8751-92e40654c839.png)

**Comment by liujinxing** [comment]
@maitian0222 保证最起码能看到三个字的人名。

**Comment by maitian0222** [comment]
设置授权人员宽度最少显示三个字符

**Comment by fulimin123** [comment]
测试通过
