### ISSUE TITLE
bug(智能表单后台管理)： 新建表单时出现两个偶现bug

### ISSUE THREAD

**Issue by tianyanqiu** [sinoui/sino-intellisense-form#239]
- [x] 输入表单标题，清空，再次输入表单标题，保存，提示“正在重命名表单，请稍后再保存”
- [x] 上述操作后，点击按钮退出，提示内容已修改是否保存，点击不保存，退出后表单不存在

**Comment by maitian0222** [comment]
问题一：新建表单时表单名称修改，保存时不提示“正在重命名表单，请稍后再保存”

**Comment by fulimin123** [comment]
pass
