### ISSUE TITLE
bug（智能表单后台管理）：刚打开的表单设计页，点击回退按钮，却出现了保存提示

### ISSUE THREAD

**Issue by liujinxing** [sinoui/sino-intellisense-form#24]
期望：刚打开表单设计页，点击回退按钮，不出现保存提示。

**Comment by maitian0222** [comment]
旧 表单错误数据会有该问题。因为调用接口获取表单数据时formConfig返回为null。但是表单设计器组件初始化是触发了表单设计器的onChange事件，formConfig被赋值为默认值。数据改变，所以会提示。
