### ISSUE TITLE
当第一个文本框默认为系统标题，发送到流程中，处长节点修改了第一个文本框的内容后，待办列表中标题未回显。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#244]
第一个文本框默认为系统标题，发布后，起草，发送到流程中，处长节点修改了第一个文本框的内容后，存在的问题：改后内容在待办列表中标题栏中未回显出来。
![图1](https://user-images.githubusercontent.com/59549153/72322211-c1c97100-36e0-11ea-9169-f6377edc1ac6.png)

**Comment by liujinxing** [comment]
待办标题是发送过来时产生的，之后不会再修改。 @fulimin123

**Comment by fulimin123** [comment]
pass
