### ISSUE TITLE
按成员授权时，被授权人员名字显示不全

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#245]
![现象](https://user-images.githubusercontent.com/59549153/72333957-98680f80-36f7-11ea-979e-35534ade5e3a.png)

**Comment by maitian0222** [comment]
名字最少显示三个字，当鼠标移上名字会显示出全部名称

**Comment by liujinxing** [comment]
@maitian0222 做成展现完整名字的效果。名字一般不会太长。

**Comment by fulimin123** [comment]
测试通过
