### ISSUE TITLE
新建一个表单，授权肖战为数据查看人员，发布审核通过后，肖战没有该表单

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#246]
操作步骤：新建一个表单，授权肖战为数据查看人员，发布审核通过后，起草完一条数据后，登录肖战，左侧列表中没有新建的该表单。
新建表单为：01-15

![a](https://user-images.githubusercontent.com/59549153/72401679-a6657100-3787-11ea-9f6b-ba455c144a6c.png)
![b](https://user-images.githubusercontent.com/59549153/72401697-b2513300-3787-11ea-8644-76ce1340bdd7.png)

**Comment by wxz0107** [comment]
![image](https://user-images.githubusercontent.com/8895642/72497008-5a3d2e00-3866-11ea-9d51-e414591eeb4d.png)
这不存在吗？？
