### ISSUE TITLE
流程设计节点，允许内部流转，范围是直属单位，应用后，内部流转时显示的是跨部门单位人员

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#247]
问题：流程设计节点，允许内部流转时范围选择的是直属单位，应用后，内部流转时显示的是跨部门单位人员。
可使用01-15复现问题现象。在“司长审批节点2”设置内部流转时范围为直属单位，流程发到这个节点可看到现象。
![现象1](https://user-images.githubusercontent.com/59549153/72401964-88e4d700-3788-11ea-9c4b-aa2db971da5d.png)
![现象2](https://user-images.githubusercontent.com/59549153/72401971-900be500-3788-11ea-9397-ce1abba2125e.png)

**Comment by fulimin123** [comment]
如果同部门的含义是：B节点的参与者所在部门与A节点参与者所在部门有相同的父部门。那么当前这个问题不属于bug。

**Comment by liujinxing** [comment]
@fulimin123 你上面描述的是直属部门的含义。
