### ISSUE TITLE
现象：点击完一个流程节点，鼠标直接点击下一个流程节点，此时上一个流程节点仍是选中状态。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#248]
现象：点击完一个流程节点，鼠标直接点击下一个流程节点，此时上一个流程节点仍是选中状态。
建议：鼠标点击下一流程节点后，取消上一节点的选中状态。
备注：此为火狐浏览器中的现象，谷歌浏览器正常。
![问题现象](https://user-images.githubusercontent.com/59549153/72402760-22ad8380-378b-11ea-923b-68024155df47.png)

**Comment by tianyanqiu** [comment]
此现象无法复现，需要确认操作时是否误触`Ctrl`键。如果是在`Ctrl`+ 点击的情况下出现，属正常现象
