### ISSUE TITLE
在表单发布页面修改表单，拖拽到左侧，第一次点击发布，出现提示如截图

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#253]
操作步骤：表单名称命名完毕，表单设计和流程设计完毕，在表单发布页面，修改了左上角的表单名称，点击保存按钮，然后拖拽到左侧，点击发布，此时提示
![123](https://user-images.githubusercontent.com/59549153/72420651-17be1780-37ba-11ea-9fbb-c3231a77714a.png)

**Comment by liujinxing** [comment]
@fulimin123 应该是表单名称发生变化了，就会有此提示。确认一下是否是这样？

**Comment by maitian0222** [comment]
出现提示语的规则是: 表单是已发布状态同时表单名称被修改，可以基于此规则做验证。

**Comment by fulimin123** [comment]
pass
