### ISSUE TITLE
单选按钮组，选择后取消不了，必须要选择一个；

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#258]
问题：单选按钮组，选择后取消不了，必须要选择一个；
建议：按钮选择后可以取消，可以不选择。（若为非必填项时为什么非让人选择呢）
![1](https://user-images.githubusercontent.com/59549153/72499894-11897300-386e-11ea-87dd-78b140c5884d.png)

**Comment by maitian0222** [comment]
单选按钮的默认规则就是这样，如果想取消当前选项，只能选中其他选项。

**Comment by liujinxing** [comment]
@tianyanqiu 看看其他的ui库和网站的按钮组组件是怎么处理的。
