### ISSUE TITLE
系统中不支持“年-月”的格式

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#263]
日期格式选择“年-月”，预览及起草页面不支持该格式；
若不支持，建议可删除该选项。
![日期格式](https://user-images.githubusercontent.com/59549153/72501784-bd34c200-3872-11ea-91c0-3b86f660f0a4.png)

**Comment by liujinxing** [comment]
@maitian0222 DatePicker 组件应该是支持年月模式的。

**Comment by fulimin123** [comment]
pass
