### ISSUE TITLE
表单字段校验添加校验规则扩展性

### ISSUE THREAD

**Issue by maitian0222** [sinoui/sino-intellisense-form#267]

**Comment by liujinxing** [comment]
通用校验规则：

```tsx
const formConfigBuilder = ...;
formConfigBuilder.validate('required', requiredFn);
formConfigBuilder.validate('min', minFn);
```

针对单个字段的校验规则在定义字段的子模块中添加，如：

```tsx
const fieldConfig = {
  type: 'addressSelect',
  label: '地址选择器',
  validates: {
    required: addressSelectRequiredFn,
  },
}
```

在校验某个字段的值时，字段校验规则优先级高于通用校验规则，且如果有字段校验规则，则不使用通用校验规则。

内置的校验规则包括：

* required
* min
* max
* minLength
* maxLength
* range

内置校验规则优先级最低。

对于校验规则函数，类似如下：

```tsx
interface ValidateFunction {
  (value: any, validateRule: ValidateRule, context: { props: any; formState: FormState; }):
    | string
    | null
    | undefined;
}
```

参数说明：

* value - 需要校验的字段值
* validateRule - 用户在表单设计器中设置的校验规则配置
* context - 字段上下文
  * props - 用户在表单设计器中的字段配置
  * formState - 表单状态。可以从formState中取到其它字段的值。
