### ISSUE TITLE
权限处理、高级搜索项都需要调整为取Field的fieldName值而不是id

### ISSUE THREAD

**Issue by maitian0222** [sinoui/sino-intellisense-form#271]
需要新建表单测试以下几点：
1.流程节点设置字段权限保存，各流程节点的数据填报页面字段权限是否一致
2.查询列表自定义列、高级搜索功能是否符合预期

**Comment by maitian0222** [comment]
需要新建表单测试以下几点：
1.流程节点设置字段权限保存，各流程节点的数据填报页面字段权限是否一致
2.查询列表自定义列、高级搜索功能是否符合预期

**Comment by fulimin123** [comment]
回测：
1.流程设计中某一节点某一字段或子表单设置不可见，保存后。流程走到该节点，办理完毕后，在该节点已办列表中，本不可见的字段都显示了出来。
2.在查询列表-自定义列表中，该节点不可见的字段也展示了出来。
![1](https://user-images.githubusercontent.com/59549153/74711069-073c0980-525e-11ea-947d-029d52871a80.png)
![2](https://user-images.githubusercontent.com/59549153/74711099-19b64300-525e-11ea-9746-0603926deb1e.png)
![3](https://user-images.githubusercontent.com/59549153/74711173-48341e00-525e-11ea-9d1d-944a6e64810b.png)

**Comment by maitian0222** [comment]
@fulimin123 查询列表自定义列和高级搜索的选项列表不做字段权限可见和只读的控制。

**Comment by wxz0107** [comment]
在测试表单 的已办列表 中点开数据 子表单隐藏。

**Comment by fulimin123** [comment]
pass
