### ISSUE TITLE
流程设计器绘制完毕后，保存表单数据，flowConfig中lines长度和页面实际显示的路由条数不一致。（偶然出现，还没找到发生问题产生的规律）

### ISSUE THREAD

**Issue by maitian0222** [sinoui/sino-intellisense-form#28]
![微信图片_20191202132941](https://user-images.githubusercontent.com/25222222/69932930-e3dbab00-1507-11ea-8fe9-2a0184b390fe.png)

**Comment by liujinxing** [comment]
没有排查出问题。再出现类似问题，按照下面的步骤记录一下问题：

## 步骤一

收集程序的输出日志：打开控制台，收集以下日志：

![image](https://user-images.githubusercontent.com/1055306/69936338-75e8b100-1512-11ea-8d2a-b92ec0df0699.png)

将最后四条日志的对象数据展开到上图的级别。

## 步骤二

收集 Redux 日志：打开Redux开发者工具，选择最后一个流程设计器，如下图所示：

![image](https://user-images.githubusercontent.com/1055306/69936595-32db0d80-1513-11ea-824b-5cdf4d11057b.png)

之后点击右下角的导出按钮，将状态导出：

![image](https://user-images.githubusercontent.com/1055306/69936703-84839800-1513-11ea-84e6-94fbf9445a48.png)

并上传到 issue 中。

## 步骤三

收集一下请求的内容和响应的内容：

![image](https://user-images.githubusercontent.com/1055306/69936848-f22fc400-1513-11ea-9ce9-ac492d942a8c.png)

![image](https://user-images.githubusercontent.com/1055306/69936893-0e336580-1514-11ea-9275-b4433c5cdf38.png)

**Comment by liujinxing** [comment]
原因：多出来的一根线是自己送给自己的，而且是同一个边。
