### ISSUE TITLE
创建时间按照等于和不等于某一天查询时，查询不出结果

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#280]
现象：创建时间如果填写某一天，查询条件选择“等于”和“不等于”时是查询不出正确结果的 ，因为创建时间包含时分秒，用户应该不会具体到时分秒
![创建时间](https://user-images.githubusercontent.com/59549153/72610730-20058680-3963-11ea-9418-eac1539e6587.png)

**Comment by liujinxing** [comment]
@tianyanqiu 在收集日期选择组件的值时，需要根据日期格式，对日期进行格式化处理。

**Comment by liujinxing** [comment]
高级检索中针对“创建时间”做优化：

* 查询条件值用日期选择框选择
* 查询条件关系定制为：早于（gte）、晚于（lte）、等于（equal）、不等于（notEqual）、为空（null）、不为空（notNull）

对于日期字段，也做一下优化：

* 查询条件关系添加上：早于（gte）、晚于（lte）。

**Comment by fulimin123** [comment]
pass
