### ISSUE TITLE
高级检索中，单选按钮组、复选框组、部门选择、用户选择、状态这几项中使用各自的查询条件都查不出结果

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#281]
高级检索中，单选按钮组、复选框组、部门选择、用户选择、状态这几项中使用各自的查询条件都查不出结果
![单选按钮组](https://user-images.githubusercontent.com/59549153/72610183-b8027080-3961-11ea-9191-35dce0ceb139.png)

**Comment by wxz0107** [comment]
已修复，已部署 请测试

**Comment by fulimin123** [comment]
回测：表单为2-10测试，使用汪芳/12345678登录，在查看列表中，存在以下问题
![创建时间为空时，查出了这条数据](https://user-images.githubusercontent.com/59549153/74135471-4e574880-4c27-11ea-8ea7-d539a90d3201.png)
![地址选择-新](https://user-images.githubusercontent.com/59549153/74135483-54e5c000-4c27-11ea-9a52-12e6e3ecd669.png)
![复选框组-不包含](https://user-images.githubusercontent.com/59549153/74135501-5fa05500-4c27-11ea-940e-eaea3e69e347.png)
![选择横线过长，与其他选项不一致](https://user-images.githubusercontent.com/59549153/74135551-7050cb00-4c27-11ea-922e-310222d767e7.png)

**Comment by liujinxing** [comment]
地址选择查询失败的原因：

存储的地址选择的数据是：

![image](https://user-images.githubusercontent.com/1055306/74208585-27e4ec00-4cbf-11ea-9b28-18f47e6a5c68.png)

但是列表中展现的是：

![image](https://user-images.githubusercontent.com/1055306/74208631-611d5c00-4cbf-11ea-8d48-b40f79ee7be6.png)

用户很有可能用列表中展现的地址值作为查询条件进行检索，这样就查询不出来想要的结果。

@maitian0222 将地址选择的查询值调整为与展现值一致。

**Comment by liujinxing** [comment]
复选框的不包含关系使用 `notContain` 关系。 @maitian0222

**Comment by liujinxing** [comment]
@fulimin123 创建时间没有为空、不为空的查询关系了。

**Comment by fulimin123** [comment]
回测：
1、地址选择中的几个查询条件仍不好用；
2、复选框组的不包含不好用；

**Comment by liujinxing** [comment]
@fulimin123 确认一下：使用新建的数据进行测试的么？我刚用汪芳的“2-11未命名”的查询列表进行验证，是没有问题的。

**Comment by fulimin123** [comment]
pass
