### ISSUE TITLE
字段属性面板出现双标题

### ISSUE THREAD

**Issue by maitian0222** [sinoui/sino-intellisense-form#283]
![image](https://user-images.githubusercontent.com/20694684/72661805-b2686180-3a19-11ea-9fd4-82611242b331.png)

**Comment by liujinxing** [comment]
应该是因为多个版本的 @sinoui/rx-form-state 的原因导致的。我在主分支上已经无法复现了。

**Comment by fulimin123** [comment]
目前只做表单时未出现该现象。
