### ISSUE TITLE
角色授权列表排序建议调整一下

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#300]
![角色排序](https://user-images.githubusercontent.com/59549153/74118446-6bbfee80-4bf6-11ea-9a07-871ec723b475.png)

**Comment by maitian0222** [comment]
![image](https://user-images.githubusercontent.com/20694684/74299636-46fb8080-4d88-11ea-9cb4-3887d029907c.png)
新增角色后需要在授权系统 的角色管理列表调整角色顺序，智能表单中的角色顺序和授权系统中的角色顺序保持一致。
