### ISSUE TITLE
省市县都填写完毕，必填项校验仍存在。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#302]
![问题](https://user-images.githubusercontent.com/59549153/74120219-7fbb1e80-4bfd-11ea-8552-2fb0d1141c69.png)

**Comment by fulimin123** [comment]
回测：
1.必填项校验的问题已解决
2.地址选择为必填项时，缺少*号标识
![星号标识](https://user-images.githubusercontent.com/59549153/74140571-4223b900-4c30-11ea-913c-3bface294028.png)

**Comment by fulimin123** [comment]
把“地址选择”设置为必填，在预览中，仍没有星号标记。

**Comment by liujinxing** [comment]
@fulimin123 不好意思，没有部署就让你测试了。
