### ISSUE TITLE
起草页面创建时间精确到时、分、秒，而查询条件中的创建时间“等于”，只能选择到年月日，两处不一致，所以，等于这个查询条件等于是没有用的。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#308]
![查询条件](https://user-images.githubusercontent.com/59549153/74215875-95077a00-4cdd-11ea-8b01-9fc898c2d1e7.png)

**Comment by liujinxing** [comment]
@fulimin123 创建时间的查询只精确到天。

**Comment by fulimin123** [comment]
pass
