### ISSUE TITLE
日期控件，建议增加清空的功能，日期选择完毕后，点击清除，清除掉所选日期。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#311]
![日期控件1](https://user-images.githubusercontent.com/59549153/74391793-2e4ea180-4e40-11ea-8689-1d075835032e.png)
![控件2](https://user-images.githubusercontent.com/59549153/74391804-33135580-4e40-11ea-82ca-7ad194ca619d.png)

**Comment by fulimin123** [comment]
日期区间也建议一块做下调整。

**Comment by liujinxing** [comment]
与 #259 重复
