### ISSUE TITLE
bug（智能表单应用）：流程日志展示不全

### ISSUE THREAD

**Issue by liujinxing** [sinoui/sino-intellisense-form#32]
出差申请单，从处员起草发送到处长，在处长审批节点显示的流程日志信息不全，如下图所示：

![image](https://user-images.githubusercontent.com/1055306/69939084-eb0bb480-1519-11ea-9995-87f896a0fa64.png)

**Comment by maitian0222** [comment]
已修改，已合并到master分支上。
