### ISSUE TITLE
谷歌浏览器，表单设计中“部门选择”设置为本部门，起草页面，部门选择项选不了本部门，只能选其下级部门。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#330]
可使用汪芳登录，汪芳是公文处处员。
![谷歌浏览器](https://user-images.githubusercontent.com/59549153/74432592-d2186b80-4e99-11ea-8f8d-9a821cf79cef.png)

**Comment by maitian0222** [comment]
@wxz0107 需要把本部门节点selectable设置为 true

**Comment by fulimin123** [comment]
pass

**Comment by wxz0107** [comment]
已修改
