### ISSUE TITLE
子表单中，多个相同基础字段，但是输入内容不同，导出后，导出了相同的内容。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#356]
1.子表单中，多个相同基础字段，但是输入内容不同，导出后，导出了相同的内容。
建议：输入什么导什么，有就导出，没有就空着。
![子表单导出问题](https://user-images.githubusercontent.com/59549153/74644530-5f690200-51b1-11ea-9767-4cc1ab36d075.png)

**Comment by liujinxing** [comment]
@fulimin123 字段的标题别是相同的，打印输出是通过字段标题取值，标题一样取值必然会出错了。
