### ISSUE TITLE
节点负责人可选择“组织架构、角色、成员”，选择完成后，点击已选择的角色能定位到列表中该位置。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#363]
建议优化：1.节点负责人可选择“组织架构、角色、成员”，选择完成后，点击选择的组织架构或该角色或该成员，可直接展开列表并定位到选择的相应位置。
      2.当负责人选择角色，设置所选业务角色所在部门范围时，选择完毕，点击后也要增加定位的功能。
优化原因：当前选择完毕后，无法判断选择的是哪个机构（重名机构）、以及哪个机构下的哪个角色
                 （重名角色）、或者哪个机构下的人（重名用户）
![建议优化内容](https://user-images.githubusercontent.com/59549153/74713405-7ec06780-5263-11ea-87e0-7b2fa68a626d.png)

**Comment by maitian0222** [comment]
@fulimin123 暂时不做此优化。
