### ISSUE TITLE
已办列表：下拉选项，名称较长时，选项内容和后面字段会有重叠部分。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#364]
![文本名称较长](https://user-images.githubusercontent.com/59549153/74795280-7d914800-5300-11ea-8641-bc03105d3758.png)

**Comment by liujinxing** [comment]
@maitian0222 直接在field-select模块中添加额外的样式处理一下。

**Comment by fulimin123** [comment]
pass
