### ISSUE TITLE
路由节点不设置“返回给发送者、是否允许返回”，保持默认设置后，在流程中默认设置不起作用。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#384]
1.起草人发科长路由，“返回给发送者、是否允许返回”都是默认设置
2.科员王帅起草流程，发科长，科长再点击发送，此时没有返回王帅的选项
![附件1](https://user-images.githubusercontent.com/59549153/77874555-d77e1980-727f-11ea-9bd1-720a747432dd.png)
![附件2](https://user-images.githubusercontent.com/59549153/77874569-de0c9100-727f-11ea-8c32-9a1f99e18523.png)

**Comment by maitian0222** [comment]
已修复
