### ISSUE TITLE
科长到处员，路由设置允许返回，流程中，处员点击发送后，未弹出返回的选项

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#386]
![附件1](https://user-images.githubusercontent.com/59549153/77884006-cdb3e080-7296-11ea-8513-444ae040fbe5.png)
![附件2](https://user-images.githubusercontent.com/59549153/77884017-d3a9c180-7296-11ea-8515-cbd57c231e70.png)

**Comment by maitian0222** [comment]
已修复。
