### ISSUE TITLE
处长节点内部流转时，发送不出去，提示“没有得到待办人”

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#387]
![流程设计](https://user-images.githubusercontent.com/59549153/77887055-7d3f8180-729c-11ea-9bf0-0a50389f314d.png)
![内部流转后发送失败](https://user-images.githubusercontent.com/59549153/77887056-7dd81800-729c-11ea-8f6b-5dc62ac8e5c3.png)

**Comment by maitian0222** [comment]
经验证，流转到处长节点发送时，没有显示出“送处长(内部流转)”路由。
![image](https://user-images.githubusercontent.com/20694684/77977534-83803d00-7332-11ea-92bc-17a4eb18f2e8.png)
