### ISSUE TITLE
设置会签节点后，在工作流中，开始节点发送到会签节点，会签节点再次发送时，无法返回开始节点。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#391]
设置会签节点后，在工作流中，开始节点发送到会签节点，会签节点再次发送时，无法返回开始节点，工作流死掉了。
![开始会签设计](https://user-images.githubusercontent.com/59549153/77894148-79fdc300-72a7-11ea-9c18-30b7d02de0d0.png)

题外：我猜测如果会签返回的的条件是“是否允许返回”必须为“是”，那用户选择“否”了，也是返不回去的。

**Comment by wxz0107** [comment]
142已经验证
