### ISSUE TITLE
设置跨部门会签，发送会签节点时，报没有下一办理人的提示

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#393]
王帅登陆，逐步发送到戴纲，戴纲选择“送处长（跨部门一级会签）
![跨部门设计](https://user-images.githubusercontent.com/59549153/77905953-b2a69800-72b9-11ea-93b3-c156380b6b9e.png)
![处长发送同级跨部门会签单位时发送失败](https://user-images.githubusercontent.com/59549153/77905965-b5a18880-72b9-11ea-9ee9-8bb279fcb584.png)

**Comment by wxz0107** [comment]
142 已经部署 统一用户修改的
