### ISSUE TITLE
节点设置为“内部流转”，流程流转到该节点点击发送，没有出现内部流转的路由。

### ISSUE THREAD

**Issue by maitian0222** [sinoui/sino-intellisense-form#401]
![image](https://user-images.githubusercontent.com/20694684/77984210-7fa8e680-7343-11ea-9453-b6220873bfac.png)
![image](https://user-images.githubusercontent.com/20694684/77984253-9bac8800-7343-11ea-99e5-9511faee2818.png)

**Comment by wxz0107** [comment]
已修复
