### ISSUE TITLE
建议：会签时选择两个会签负责人，第一个人办理结束的流程状态描述容易引起歧义。

### ISSUE THREAD

**Issue by tianyanqiu** [sinoui/sino-intellisense-form#404]
会签节点选择两个负责人，第一个人处理完发送时，路由提示“结束办理”有歧义，流程记录中也显示“结束办理”。

![image](https://user-images.githubusercontent.com/25222222/77985709-c1d42700-7347-11ea-8b33-95df26fc4e5e.png)

**Comment by liujinxing** [comment]
与 #380 重复。
