### ISSUE TITLE
bug: 流程流转至结束流程的上一节点，点击发送会提示“是否确认办结”，点完确定，又出现选路由界面。

### ISSUE THREAD

**Issue by tianyanqiu** [sinoui/sino-intellisense-form#407]
问题描述：

流程（会签流程测试）：
![image](https://user-images.githubusercontent.com/25222222/77999571-7761a300-7365-11ea-95cf-8262339b167d.png)
流转顺序：
科员起草-->科长审批--> 文书中转-->司长审批

当前节点：
司长审批

问题截图:
![image](https://user-images.githubusercontent.com/25222222/77999691-ad068c00-7365-11ea-972a-5a5c028e929b.png)

**Comment by maitian0222** [comment]
已修复。
