### ISSUE TITLE
建议优化：已办列表显示当前流程状态

### ISSUE THREAD

**Issue by DragonCloudsBai** [sinoui/sino-intellisense-form#430]
![image](https://user-images.githubusercontent.com/11955014/78887570-b0e78c00-7a92-11ea-9ccd-0f7f42660f11.png)已办列表建议加上一列显示当前数据是在流转中还是已办结，方便用户查看

**Comment by maitian0222** [comment]
与issue425是同一个问题，已经在v1.2.4版本修复的此问题。
