### ISSUE TITLE
建议优化：查询列表中状态为默认展示字段

### ISSUE THREAD

**Issue by DragonCloudsBai** [sinoui/sino-intellisense-form#431]
![image](https://user-images.githubusercontent.com/11955014/78887940-5995eb80-7a93-11ea-9c27-4a9218516b10.png)

建议将状态设置为默认展示字段

**Comment by maitian0222** [comment]
@liujinxing 需要讨论，状态作为默认字段有两种方式：

**Comment by liujinxing** [comment]
@maitian0222 选择第一种方案。
