### ISSUE TITLE
路由设置基础属性有问题时，下一节点人可以收到邮件

### ISSUE THREAD

**Issue by zhanghaijuan186186** [sinoui/sino-intellisense-form#433]
![路由设置问题截图](https://user-images.githubusercontent.com/63399671/78989588-9b439680-7b66-11ea-90d8-9cc45aaaa0b3.png)
![王帅收到待办消息截图](https://user-images.githubusercontent.com/63399671/78989596-9f6fb400-7b66-11ea-9f36-00bbd8b1804f.png)

**Comment by maitian0222** [comment]
同 issue #434 是同一类问题。只有节点负责人设置为角色时，才需要设置部门范围和部门级别。负责人选择为组织结构或人员时，因为人负责人直接的关系已经确定，不论是否设置了部门范围和部门级别，流程都可以正常流转。
