### ISSUE TITLE
路由基础属性设置有问题时，下一节点人可以收到待办信息

### ISSUE THREAD

**Issue by zhanghaijuan186186** [sinoui/sino-intellisense-form#434]
![1](https://user-images.githubusercontent.com/63399671/78991127-caf49d80-7b6a-11ea-8beb-f6317b15cbe6.png)
![2](https://user-images.githubusercontent.com/63399671/78991135-ce882480-7b6a-11ea-9dc1-7b4880ffb89e.png)
![3](https://user-images.githubusercontent.com/63399671/78991145-d2b44200-7b6a-11ea-8ca6-e50760d1b9af.png)
![4](https://user-images.githubusercontent.com/63399671/78991151-d6e05f80-7b6a-11ea-8d7a-1b31e81f3bf4.png)
![5](https://user-images.githubusercontent.com/63399671/78991157-da73e680-7b6a-11ea-96a0-8c1741239e25.png)
![6](https://user-images.githubusercontent.com/63399671/78991159-dd6ed700-7b6a-11ea-8070-3edf77bef3aa.png)
当路由基础属性错误设定状态下，点击发送时，下一节点人可以收到待办消息

**Comment by maitian0222** [comment]
@zhanghaijuan186186 这样设置应该是正确的，路由上部门范围和部门级别各选项含义如下图所示：
![image](https://user-images.githubusercontent.com/20694684/79108880-d84b9b00-7da9-11ea-82b9-d5a9fc6f74e3.png)
![image](https://user-images.githubusercontent.com/20694684/79108936-f3b6a600-7da9-11ea-8ef1-b6eb325ac634.png)
![image](https://user-images.githubusercontent.com/20694684/79108950-f9ac8700-7da9-11ea-9fd5-5cc34e9199f0.png)

**Comment by maitian0222** [comment]
古亚文节点发送给王先生节点，路由跨门部门上级设置确实存在问题。
