### ISSUE TITLE
通过统一授权管理系审核后，呈现同一名称表单重出状态

### ISSUE THREAD

**Issue by zhanghaijuan186186** [sinoui/sino-intellisense-form#439]
![表单重复图](https://user-images.githubusercontent.com/63399671/79304436-e8878580-7f23-11ea-89e2-db99a3a7e60e.png)

通过统一授权管理系审核后，呈现同一名称表单重出状态，偶尔出现此状态

**Comment by maitian0222** [comment]
是因为在统一授权管理系统中，审核通过按钮多次点击造成的重复数据。已修复。
