### ISSUE TITLE
会签状态下，上一节点人已处理待办信息，下一节点人未收到待办信息

### ISSUE THREAD

**Issue by zhanghaijuan186186** [sinoui/sino-intellisense-form#442]
![古亚文、戴纲未收到韩桂明发来的待办信息](https://user-images.githubusercontent.com/63399671/79427870-eee73180-7ff7-11ea-8653-6559ef961878.png)

流程日志中有发送记录，当前节点人未收到待办信息

**Comment by maitian0222** [comment]
暂未复现此问题。复现时再打开。
