### ISSUE TITLE
处理2条待办信息后，查看已办信息记录只有1条

### ISSUE THREAD

**Issue by zhanghaijuan186186** [sinoui/sino-intellisense-form#447]
![image](https://user-images.githubusercontent.com/63399671/79631615-11f71a00-818d-11ea-93f4-7184fecef957.png)
![image](https://user-images.githubusercontent.com/63399671/79631616-16233780-818d-11ea-9212-d56c8f915a35.png)

**Comment by maitian0222** [comment]
@zhanghaijuan186186 同一条数据，在已办列表中只存在一条是正常的。
