### ISSUE TITLE
无法办理结束

### ISSUE THREAD

**Issue by zhanghaijuan186186** [sinoui/sino-intellisense-form#448]
![image](https://user-images.githubusercontent.com/63399671/79631651-584c7900-818d-11ea-8072-807b4644b515.png)
![image](https://user-images.githubusercontent.com/63399671/79631653-5be00000-818d-11ea-8f88-c44d64b17e89.png)
![image](https://user-images.githubusercontent.com/63399671/79631656-600c1d80-818d-11ea-9054-d06365e4ecd5.png)

会签状态下，同一节点两个用户无法办理结束，分别登录账户点击结束都时，都提示：发送失败，其它待办用户还在办理中，暂时不能结束整个流程，请等待（如图3）

**Comment by maitian0222** [comment]
@zhanghaijuan186186 这是正常的。只有最后一个会签分支选择“送结束节点”才可以结束办理。其他会签分支时，结束办理时都会显示此提示语。
