### ISSUE TITLE
多级会签时，同样无法送结束节点

### ISSUE THREAD

**Issue by zhanghaijuan186186** [sinoui/sino-intellisense-form#450]
![image](https://user-images.githubusercontent.com/63399671/79641349-8c458f80-81c9-11ea-90d3-d0ed98d8d5e5.png)
![image](https://user-images.githubusercontent.com/63399671/79641351-8fd91680-81c9-11ea-97ce-51f22c33ac40.png)

多级会签状态下，陈振林、部门经理登录收到待办无法送结束节点

**Comment by maitian0222** [comment]
@zhanghaijuan186186 同#448是一个问题。
