### ISSUE TITLE
咨询：是否可以关闭表单发布的审批环节，点击发布即可完成？

### ISSUE THREAD

**Issue by liujinxing** [sinoui/sino-intellisense-form#454]

**Comment by maitian0222** [comment]
需要分以下情形进行测试：
1. 统一配置设置中 是否开启表单审核 设置为 “否”，是否开启安全审计 为“是”或者“否”，在智能表单设计中发布表单，都不需要在统一授权 平台中审核，就可以在系统中看到表单资源。
2. 统一配置设置中 是否开启表单审核 设置为 “是”，是否开启安全审计 为“是”，在智能表单设计中发布表单，需要在统一授权中进行“业务流程授权”和“系统操作审核”两步审核操作成功后才可以在系统中显示该表单资源。
3. 统一配置设置中 是否开启表单审核 设置为 “是”，是否开启安全审计 为“否”，在智能表单设计中发布表单，只需在统一授权中进行“业务流程授权”成功后就可以在系统中显示该表单资源。
![image](https://user-images.githubusercontent.com/20694684/82637095-a47c5480-9c36-11ea-9da7-78b5a6be4bf0.png)
![image](https://user-images.githubusercontent.com/20694684/82636986-6848f400-9c36-11ea-924c-78952deb4062.png)
![image](https://user-images.githubusercontent.com/20694684/82637004-7860d380-9c36-11ea-9626-77d457a05aa2.png)

**Comment by fulimin123** [comment]
测试通过
