### ISSUE TITLE
选择部门为：本部门，起草时加载不出来

### ISSUE THREAD

**Issue by DragonCloudsBai** [sinoui/sino-intellisense-form#457]
选择部门为：本部门，起草时加载不出来[image](https://user-images.githubusercontent.com/11955014/79817354-e1df8f00-83b7-11ea-9ae5-cc6045683f0c.png)

**Comment by maitian0222** [comment]
@DragonCloudsBai 需要将起草时，加载不出来的截图贴一下。

**Comment by DragonCloudsBai** [comment]
![image](https://user-images.githubusercontent.com/11955014/79824336-a3060500-83c8-11ea-8312-d6b6023809d9.png)
![image](https://user-images.githubusercontent.com/11955014/79824346-a7322280-83c8-11ea-8bb4-797321d210f7.png)
我们想添加一个默认项，默认值可以选择带出本部门名称

**Comment by DragonCloudsBai** [comment]
比如有个创建单位字段，这种可以带出他部门名称就可以，也可以让他选

**Comment by maitian0222** [comment]
@DragonCloudsBai 部门选择字段，属性设置中部门范围选择为“本部门“时，只是部门组织树只显示本部门的节点。和默认显示部门名称无关。此issue描述的问题是否和 issue #459 表达的意思一样？

**Comment by maitian0222** [comment]
和459问题重复
