### ISSUE TITLE
IE11展示的时候，配置表单页面错乱

### ISSUE THREAD

**Issue by DragonCloudsBai** [sinoui/sino-intellisense-form#461]
![image](https://user-images.githubusercontent.com/11955014/79817703-aa251700-83b8-11ea-8a4b-c042905a37e4.png)
![image](https://user-images.githubusercontent.com/11955014/79817730-b1e4bb80-83b8-11ea-8de3-e7a06ba19466.png)

**Comment by maitian0222** [comment]
重复缺陷，v1.2.5版本已修复
