### ISSUE TITLE
导出时会签意见显示不全

### ISSUE THREAD

**Issue by DragonCloudsBai** [sinoui/sino-intellisense-form#462]
![image](https://user-images.githubusercontent.com/11955014/79818146-a645c480-83b9-11ea-98bd-eb0c0a1192d3.png)
![image](https://user-images.githubusercontent.com/11955014/79818151-a8a81e80-83b9-11ea-9fa9-e8755a1a0367.png)

**Comment by maitian0222** [comment]
重复缺陷，v1.2.5版本已修复
