### ISSUE TITLE
错误填写表单格式无提示语，成功发送至下一节点人以及提示语不明确问题

### ISSUE THREAD

**Issue by zhanghaijuan186186** [sinoui/sino-intellisense-form#479]
![image](https://user-images.githubusercontent.com/63399671/81274015-4ec67a80-9082-11ea-9a04-fe56cbab7a0d.png)
![image](https://user-images.githubusercontent.com/63399671/81274026-54bc5b80-9082-11ea-8adf-03a58d5f6b32.png)

**Comment by maitian0222** [comment]
1. 第一条描述使用新表单无法复现表单填写不完成提示语修改为

**Comment by fulimin123** [comment]
pass
