### ISSUE TITLE
当表单设计“数据格式”选择电话号码时，实际填写手机号码可发送成功至下一节点人，无提示语

### ISSUE THREAD

**Issue by zhanghaijuan186186** [sinoui/sino-intellisense-form#483]
![image](https://user-images.githubusercontent.com/63399671/81380087-d375cf00-913c-11ea-94d1-f0824b49d557.png)
![image](https://user-images.githubusercontent.com/63399671/81380095-d7095600-913c-11ea-84db-81886786199a.png)
![image](https://user-images.githubusercontent.com/63399671/81380101-da9cdd00-913c-11ea-8447-312111b6b5de.png)
![image](https://user-images.githubusercontent.com/63399671/81380111-dd97cd80-913c-11ea-87b6-33bc303f53ed.png)

**Comment by maitian0222** [comment]
和测试确认未复现该问题，先关闭
