### ISSUE TITLE
查询列表-查询条件选择“为空”、“不为空”时报错提示  

### ISSUE THREAD

**Issue by zhanghaijuan186186** [sinoui/sino-intellisense-form#485]
![image](https://user-images.githubusercontent.com/63399671/81504127-1a6ceb80-931a-11ea-8ad9-5adde3046645.png)
![image](https://user-images.githubusercontent.com/63399671/81504131-2062cc80-931a-11ea-919b-31bda9538dfe.png)
![image](https://user-images.githubusercontent.com/63399671/81504146-2a84cb00-931a-11ea-8668-c377dcd344d2.png)
![image](https://user-images.githubusercontent.com/63399671/81504149-307aac00-931a-11ea-8535-56da36b20a83.png)
谷歌、火狐都存在此报错现象

**Comment by fulimin123** [comment]
报错问题已解决，根据查询条件不能正确查询结果，这个问题仍存在，已提新的bug
