### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by zhanghaijuan186186** [sinoui/sino-intellisense-form#486]
![image](https://user-images.githubusercontent.com/63399671/81538854-e937fe00-93a1-11ea-86e0-cd246bdb5690.png)
![image](https://user-images.githubusercontent.com/63399671/81538886-f0f7a280-93a1-11ea-8486-b9481a626a9d.png)
![image](https://user-images.githubusercontent.com/63399671/81538906-fa810a80-93a1-11ea-96cf-f35d17a1c280.png)
![image](https://user-images.githubusercontent.com/63399671/81538919-0076eb80-93a2-11ea-8e04-2ec0ad2d9bb5.png)
谷歌浏览器显示有问题，不显示地址下面的多行文本，火狐浏览器可以显示

**Comment by fulimin123** [comment]
pass
