### ISSUE TITLE
超过最大长度限制，无提示语，并且可以发送至下一节点人

### ISSUE THREAD

**Issue by zhanghaijuan186186** [sinoui/sino-intellisense-form#487]
![image](https://user-images.githubusercontent.com/63399671/81539210-8430d800-93a2-11ea-89d8-ef6b4374d656.png)
![image](https://user-images.githubusercontent.com/63399671/81539222-885cf580-93a2-11ea-9c18-2548dbc8410d.png)
![image](https://user-images.githubusercontent.com/63399671/81539238-8bf07c80-93a2-11ea-9ae8-b91049e7370c.png)
![image](https://user-images.githubusercontent.com/63399671/81539254-901c9a00-93a2-11ea-81d7-2d44f2cac533.png)

**Comment by fulimin123** [comment]
pass
