### ISSUE TITLE
谷歌：表单设计页面拖拽多个字段，点击预览，在预览页面字段显示不全，只显示一部分。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#491]
![表单设计页面](https://user-images.githubusercontent.com/59549153/81636798-55207200-9447-11ea-80a3-d05b31cebb65.png)
![预览页面](https://user-images.githubusercontent.com/59549153/81636882-87ca6a80-9447-11ea-9ff5-cb621dec7f4f.png)

**Comment by maitian0222** [comment]
由于页面没有设置滚动条导致，和 #486 为同类问题。

**Comment by fulimin123** [comment]
pass
