### ISSUE TITLE
谷歌：把单行文本设置成多行文本后，默认值设置不了；最小行数设置后不起作用。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#492]
单行文本字段：把字段类型设置成多行文本后存在的问题如下：
1.默认值下的“自定义”“创建人”选择不了；
2.最小行数设置后不起作用
![单行文本存在的问题](https://user-images.githubusercontent.com/59549153/81637317-9a916f00-9448-11ea-9540-9a8e771b50c9.png)

**Comment by maitian0222** [comment]
已修复

**Comment by fulimin123** [comment]
pass
