### ISSUE TITLE
表单设计页面说明中存在的问题

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#500]
![表单设计页面说明中的问题](https://user-images.githubusercontent.com/59549153/81652624-9ffdb200-9466-11ea-93b5-ea44ead0ba9e.png)

**Comment by maitian0222** [comment]
@liujinxing 描述1帮助文档未添加。需要刘哥确认如何编写。
描述2错别字已修改。

**Comment by liujinxing** [comment]
在线帮助手册会在后期版本添加，目前版本不考虑。
