### ISSUE TITLE
谷歌：待办列表中的数据，点击后直接消失，再点击左侧待办列表，该条数据又会出现，点击数据又消失，一直进入不了办理页面。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#502]
谷歌：待办列表中的数据，点击后直接消失，再点击左侧待办列表，该条数据又会出现，点击数据又消失，一直进入不了办理页面。
登录戴纲查看现象
![待办数据点击后就消失](https://user-images.githubusercontent.com/59549153/81660989-0f2ad480-946e-11ea-9410-40f0809a9a8c.png)

**Comment by maitian0222** [comment]
数据问题。
