### ISSUE TITLE
谷歌：起草人发送后，在查询列表中看不到刚发走的数据

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#503]
![已办列表](https://user-images.githubusercontent.com/59549153/81662635-72b60180-9470-11ea-80ed-1d51e8c3e9b3.png)
![查询列表](https://user-images.githubusercontent.com/59549153/81662664-7a75a600-9470-11ea-967a-e14cde1f56be.png)

**Comment by wxz0107** [comment]
测试环境已经更新 重新起数据测试一下

**Comment by fulimin123** [comment]
pass
