### ISSUE TITLE
IE：字段类型为“数字”，默认值自定义， 预览后默认值没有带出来

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#505]
![数字默认值未带出](https://user-images.githubusercontent.com/59549153/81760848-ebfa3680-94fa-11ea-9299-e3a25fce3f8e.png)
![默认值123未带出](https://user-images.githubusercontent.com/59549153/81760881-03d1ba80-94fb-11ea-8900-781c0d7131c3.png)

**Comment by liujinxing** [comment]
@superstaring 此缺陷与IE无关。

**Comment by superstaring** [comment]
已修复

**Comment by fulimin123** [comment]
回测通过
