### ISSUE TITLE
IE：子表单中“单行文本、多行文本、数字”这三个字段的校验规则设置后，在预览页面都不起作。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#507]
子表单中：“单行文本、多行文本、数字”这三个字段的校验规则设置后，在预览页面都不起作用，输入不符合规则的数字等内容，系统没有给任何校验和提示。
![预览页面校验规则提示](https://user-images.githubusercontent.com/59549153/81762825-316d3280-9500-11ea-8883-4730fa8535f3.png)
![预览页面](https://user-images.githubusercontent.com/59549153/81763085-f15a7f80-9500-11ea-9a58-66acaf04abcf.png)

**Comment by fulimin123** [comment]
回测时数字校验规则存在的问题：
1.限定范围的单位没有，是位还是只能输5到10之间的数？表述不清。
2.预览页面，限定范围仍未起到任何作用。
注：子表单中数字也存在该问题。

![数字校验规则](https://user-images.githubusercontent.com/59549153/81917471-ceff5980-9607-11ea-89e2-87f7c68fd7eb.png)
![预览页面](https://user-images.githubusercontent.com/59549153/81917525-e0486600-9607-11ea-9b01-3066c0498cf5.png)

**Comment by tianyanqiu** [comment]
限定范围指的是数字值的限定范围，也就是最大最小值限制。

**Comment by fulimin123** [comment]
pass
