### ISSUE TITLE
IE：起草页面，子表单中，部门选择和用户选择字段选择部门和人员过多时，会超出文本框

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#508]
![超出文本框](https://user-images.githubusercontent.com/59549153/81766913-b3ae2480-9509-11ea-94da-a1dcfb06f8b9.png)

**Comment by fulimin123** [comment]
谷歌浏览器也存在该问题

**Comment by maitian0222** [comment]
重复缺陷
