### ISSUE TITLE
子表单的上下高度能否设计成可调节的，例如默认显示一行，可自己增加高度显示几行，和多选文本类似。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#509]
原因：下拉选项或部门选择选择人员过多时，用户查看不方便。
![子表单设计](https://user-images.githubusercontent.com/59549153/81767456-0f2ce200-950b-11ea-956b-f15d800fde1d.png)
![即使有上下滚动条，查看也不是很方便。](https://user-images.githubusercontent.com/59549153/81767529-31befb00-950b-11ea-913f-bc96cd5b97f3.png)

**Comment by liujinxing** [comment]
不考虑。
