### ISSUE TITLE
表单属性设置为边框模式，预览后，“地址选择”字段仍是标准模式，发布后起草页面地址选择也是标准模式。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#521]
![aa](https://user-images.githubusercontent.com/59549153/81823805-4b8e2b80-9567-11ea-9a34-bcc3dc7e7b41.png)
![bb](https://user-images.githubusercontent.com/59549153/81823844-5779ed80-9567-11ea-9bf3-d714e36545d0.png)
![地址选择问题](https://user-images.githubusercontent.com/59549153/81823889-69f42700-9567-11ea-9c47-ea38509124ce.png)

**Comment by maitian0222** [comment]
已处理
