### ISSUE TITLE
IE：填充模式中，“地址选择”字段样式仍为标准模式，就是这样设计的吗？

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#524]
![填充模式中“地址选择”字段](https://user-images.githubusercontent.com/59549153/81828836-d1f93c00-956c-11ea-8f85-0785fba6813c.png)

**Comment by maitian0222** [comment]
地址选择组件省市区字段有填充模式和边框模式，详情地址只有标准模式

**Comment by fulimin123** [comment]
pass
