### ISSUE TITLE
IE：点击退回，确定后，不需要再加一个确认提示了。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#528]
![没有必要再加这个确认提示](https://user-images.githubusercontent.com/59549153/81890677-233f1500-95d9-11ea-99e4-1a846e94bd06.png)

**Comment by maitian0222** [comment]
1.退回、办结之类的流程动作都有二次确认操作。
2.理由输入框没有全宽显示的样式缺陷已修复

**Comment by fulimin123** [comment]
pass
