### ISSUE TITLE
IE：常用意见中增加删除功能及选中背景功能

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#529]
建议：1.常用意见被选取后，加个背景，让人能辨别出来是选中状态，不要一闪而过。
           2.常用意见中增加删除功能，可删除不要的意见。
![常用意见](https://user-images.githubusercontent.com/59549153/81891365-c7758b80-95da-11ea-9b8f-93a5576944e6.png)

**Comment by maitian0222** [comment]
常用意见的删除暂时不实现。

**Comment by fulimin123** [comment]
pass
