### ISSUE TITLE
IE：查询条件显示不全，滑动滚动条也看不到，自定义列字段调整后，高级搜索中的查询条件也没有任何变化。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#531]
![查询条件显示不全](https://user-images.githubusercontent.com/59549153/81908306-a7a28f80-95fb-11ea-8156-4fd0a2962cee.png)

**Comment by fulimin123** [comment]
谷歌浏览器也存在该问题

**Comment by maitian0222** [comment]
1. 显示不全为Select组件通用问题
2.高级搜索中的查询条件是表单中的所有字段，不会随着自定义列的设置而变化的。

**Comment by fulimin123** [comment]
pass
