### ISSUE TITLE
苹果：移动端用户的表单列表展示不正确，多出来很多不是他可看到的表单。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#536]
分别使用“王帅”登录pc端和移动端：
pc端表单列表如下：
![pc端](https://user-images.githubusercontent.com/59549153/82003140-2fd37400-9692-11ea-96ac-1c92069c4ea8.png)
移动端表单列表如下：
![移动端](https://user-images.githubusercontent.com/59549153/82003156-3b269f80-9692-11ea-9f41-8814b43dd713.png)

**Comment by maitian0222** [comment]
已修改

**Comment by fulimin123** [comment]
pass
