### ISSUE TITLE
苹果：查询列表中没有数据时，未给出友好提示，只有白板

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#537]
建议：可显示“暂无数据”。像待办列表无数据时的显示。

![白板](https://user-images.githubusercontent.com/59549153/82003504-1b43ab80-9693-11ea-8440-665727920e91.png)

**Comment by maitian0222** [comment]
移动端暂时不显示查询列表

**Comment by fulimin123** [comment]
pass
