### ISSUE TITLE
苹果：起草页面，下拉选项字段，选项中字数较多时，会展示不全

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#539]
![1](https://user-images.githubusercontent.com/59549153/82004069-99ed1880-9694-11ea-8c40-0d253fcfda62.jpg)

![pc预览](https://user-images.githubusercontent.com/59549153/82004135-c0ab4f00-9694-11ea-8861-b596ca3a4235.png)

**Comment by liujinxing** [comment]
暂不处理。出现这种情况，建议用户使用单选按钮组或复选按钮组。

**Comment by fulimin123** [comment]
pass
