### ISSUE TITLE
苹果：附件上传，使用拍照功能拍完照片直接使用，提示文件上传失败

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#540]
![1](https://user-images.githubusercontent.com/59549153/82005057-ff420900-9696-11ea-930e-a5e4c14ad7e8.jpg)

**Comment by maitian0222** [comment]
@liujinxing 需要谢哥协助看下是什么原因导致的上传失败。初步分析是附件大小导致（上传的图片超过1M）

**Comment by liujinxing** [comment]
与 #582 是同一个缺陷。
