### ISSUE TITLE
苹果：整行布局时已办列表中只读页面字段显示问题

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#541]
1、单行文本超出文本框部分查看不了。如下图：

![附件1](https://user-images.githubusercontent.com/59549153/82011373-68ca1380-96a7-11ea-9ebb-7fec9c5ab0ac.png)

2、下拉选项超出文本部分及多个选项部分查看不了；
3、地址文字较多时显示不全。
如下图：
![附件2](https://user-images.githubusercontent.com/59549153/82011406-7e3f3d80-96a7-11ea-9eb1-5d03d9881fe9.png)

3、复选框组和单选按钮组字段与选项紧挨在一起了，如下图：
![附件3](https://user-images.githubusercontent.com/59549153/82011422-88f9d280-96a7-11ea-8420-b697c71eece9.png)

**Comment by maitian0222** [comment]
单行文本和下拉选择超出一行显示不全的问题暂不处理。描述中的地址选择和单选、复选组问题已修复、
