### ISSUE TITLE
苹果：整行布局，已办列表只读页面，子表单有删除按钮

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#542]
1.整行布局，已办列表只读页面，子表单有删除按钮
2.表单设计中，审核节点所有字段均不可编辑；应用后，在审核节点打开待办，里面的子表单存在可删除的问题。
![删除按钮](https://user-images.githubusercontent.com/59549153/82012110-87c9a500-96a9-11ea-8bd5-ac56ea4b173a.png)

**Comment by superstaring** [comment]
已修复

**Comment by superstaring** [comment]
已修复

**Comment by fulimin123** [comment]
回测：
1、已办列表中子表单可删除已修复。
2、待办中，该节点为不可编辑时，子表单仍具有删除功能。可用5-15ie-cc这个表单复现。

**Comment by superstaring** [comment]
已修复

**Comment by fulimin123** [comment]
移动端：现在是待办列表已修复；已办列表中子表单处又出现了删除的按钮。

**Comment by fulimin123** [comment]
如果流程设计时该节点没有勾选“可编辑”，那么发布后，该节点基础字段及子表单都是不可编辑、不可删除的。
以下是当前存在的问题：
1.移动端，打开待办，不可编辑的表单字段及子表单字段能编辑了。
2.pc端，不可编辑的表单及子表单能编辑，并且子表单还能删除。
3.移动端，已办列表中仍能删除子表单。

**Comment by maitian0222** [comment]
@superstaring 1,2已解决。在移动端，待办中如果子表单不可编辑时仍有子表单不应该有删除按钮，已办详情也不应该有删除按钮

**Comment by superstaring** [comment]
已修复

**Comment by fulimin123** [comment]
pass
