### ISSUE TITLE
手机预览页面：字段名称超过一定字数后就显示... ，应用后也有此问题。如果不支持，建议输入字段标题时给出校验和提示

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#547]
![字段标题](https://user-images.githubusercontent.com/59549153/82029310-6678b100-96c9-11ea-9775-8d39b172a5ea.png)

**Comment by liujinxing** [comment]
暂不支持。因为没办法预测手机屏幕宽度，所以不能够以某个精确的字数来限制标题长度。推荐用户使用“字段描述”来放较长的字段说明。
