### ISSUE TITLE
在屏幕比较窄时我的表单页布局不合理

### ISSUE THREAD

**Issue by liujinxing** [sinoui/sino-intellisense-form#554]
在屏幕比较窄时“我的表单”页布局不合理：

![image](https://user-images.githubusercontent.com/1055306/82134641-431a4700-982c-11ea-95bf-ddbdfad5b332.png)

应使用响应式布局，在屏幕比较窄时，考虑使用3列布局，更窄时，考虑2列甚至1列布局。

**Comment by fulimin123** [comment]
滑动滚轮滚动屏幕，表单都能正常显示
