### ISSUE TITLE
如果子表单有填写内容，那么点击“删除”按钮时需要给出确认功能，确认后再删除。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#560]
在起草页面和待办页面，如果子表单填写了内容，再删除时，建议增加“确认是否删除”的功能。
![删除提示](https://user-images.githubusercontent.com/59549153/82169860-5cd39100-98f5-11ea-9837-06b5dffa39e5.png)

**Comment by maitian0222** [comment]
@liujinxing 确认是否采用该建议

**Comment by superstaring** [comment]
已修复

**Comment by fulimin123** [comment]
pc端在起草页面和待办页面删除子表单时没有给出提示

**Comment by superstaring** [comment]
已修复

**Comment by fulimin123** [comment]
pass
