### ISSUE TITLE
拟稿人收回后，流程日志显示异常

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#561]
操作步骤：1、起草人“王帅”发送处长“戴纲”节点，处长点击退回按钮，退回起草人
                  2、起草人在待办列表中重新发送到处长，然后在已办列表中点击收回。
流程日志现象：1、处长节点显示为“收回”
                         2、开始节点显示为“戴纲”
![问题现象](https://user-images.githubusercontent.com/59549153/82171176-23048980-98f9-11ea-8150-90a6cebc5bc8.png)

**Comment by maitian0222** [comment]
页面流程日志用户名优先显示sendname, sendname没有的值话显示receivename

**Comment by fulimin123** [comment]
截图中 1 在戴纲这里显示“收回”不合理。
原因是，其他节点都是显示的当前节点做了什么操作，而戴纲这里的当前操作是“收回”，但是收回不是他操作的，所以不应该显示收回。

**Comment by liujinxing** [comment]
@maitian0222 对于“收回”，应显示为“被收回”。

**Comment by fulimin123** [comment]
pass
