### ISSUE TITLE
苹果：填写意见页面，选择完常用意见后，没有回显在填写意见框中，而是直接关闭页面了。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#562]
![移动端填写意见框](https://user-images.githubusercontent.com/59549153/82172209-24838100-98fc-11ea-8e4a-fb6c7072354a.png)

**Comment by maitian0222** [comment]
@liujinxing 当初讨论时是点击常用意见直接采用该意见，不需要回写再关闭。需要确定是否按照建议修改

**Comment by maitian0222** [comment]
![image](https://user-images.githubusercontent.com/20694684/82282449-72fd5200-99c6-11ea-86ec-aa7b7cf1f839.png)
![image](https://user-images.githubusercontent.com/20694684/82282451-755fac00-99c6-11ea-9a17-a961ff8a0a48.png)
@fulimin123 常用意见选择按照建议修改并增加推荐意见(同意和不同意)。当用户的常用意见中包含（同意和不同意）意见时，过滤掉系统的推荐意见。

**Comment by fulimin123** [comment]
pass

**Comment by fulimin123** [comment]
苹果机版本回显没有问题了，目前安卓手机中还存在不回显这个问题。
