### ISSUE TITLE
苹果：点击盖章后，出现的公章无法移动

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#563]
![公章无法移动](https://user-images.githubusercontent.com/59549153/82172397-9eb40580-98fc-11ea-9573-9c69f3121833.png)

**Comment by maitian0222** [comment]
@fulimin123 移动端不支持盖章功能，会屏蔽盖章按钮的显示。

**Comment by fulimin123** [comment]
pass
