### ISSUE TITLE
移动端签名功能不显示

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#565]
![pc段签名](https://user-images.githubusercontent.com/59549153/82173861-55b28000-9901-11ea-9612-68ec46e13842.png)
在移动端没有签名功能，登录陈振林可看到现象.
![签名](https://user-images.githubusercontent.com/59549153/82173875-5f3be800-9901-11ea-9868-3c15c9ec2ce2.png)

**Comment by maitian0222** [comment]
@fulimin123 移动端不支持签名和盖章功能。移动端会屏蔽这两个按钮的显示、
