### ISSUE TITLE
pc端：表单部门选择字段本部门选择出错

### ISSUE THREAD

**Issue by DragonCloudsBai** [sinoui/sino-intellisense-form#571]
配置：
![image](https://user-images.githubusercontent.com/11955014/82189652-4b54ae00-9922-11ea-8a0e-bd885132721a.png)

现象：部门树加载不出来
![image](https://user-images.githubusercontent.com/11955014/82189314-c10c4a00-9921-11ea-836d-f05fa99166ba.png)

![image](https://user-images.githubusercontent.com/11955014/82189938-d3d34e80-9922-11ea-97b3-0fde6c6a83fa.png)
console报错信息：
![image](https://user-images.githubusercontent.com/11955014/82197286-637dfa80-992d-11ea-8d85-29ba8a8c0251.png)

**Comment by liujinxing** [comment]
以某个部门作为根节点，就会有问题。例如：部门选择字段，选择部门范围为“本部门”，用处员一、司长一登录，填写表单，就会有这个问题。

**Comment by liujinxing** [comment]
@wxz0107 获取子部门的响应有问题：

## 第一次发的请求

请求url： `http://121.30.232.162:18880/apis/intellisense-form/common/getDeptAndUserInfo?type=dept&deptRange=selfDept&deptId=4028d00e6ec42073016ec466150c000e&userId=4028d00e6ec42073016ec4728d9d0043`

响应是：

```json
[
  {
    "name":"办公室",
    "id":"4028d00e6ec42073016ec466150c000e",
    "title":"办公室",
    "leaf":false,
    "children":[],
    "selectable":true,
  }
]
```

这次返回的响应没有问题。获取的是本部门信息。

## 第二次发的请求

请求url： `http://121.30.232.162:18880/apis/intellisense-form/common/getDeptAndUserInfo?type=user&deptRange=selfDept&deptId=4028d00e6ec42073016ec466150c000e&userId=4028d00e6ec42073016ec4728d9d0043`

响应是：

```json
[
  {
    "name": "办公室",
    "id": "4028d00e6ec42073016ec466150c000e",
    "title": "办公室",
    "leaf": false,
    "children": [
      {
        "uuid": "4028d00e6ec42073016ec4728d9d0043",
        "uupid": "4028d00e6ec42073016ec466150c000e",
        "name": "处员一",
        "treeId": "",
        "superTreeId": "",
        "type": "user",
        "deptlevel": "",
        "peak_deptId": "",
        "order_no": "",
        "historyId": "",
        "historycode": "",
        "id": "4028d00e6ec42073016ec4728d9d0043",
        "title": "处员一",
        "leaf": true,
        "children": [],
        "selectable": true
      },
      {
        "uuid": "4028d00e7032610b0170a8f6f079022d",
        "uupid": "4028d00e6ec42073016ec466150c000e",
        "name": "处长三",
        "treeId": "",
        "superTreeId": "",
        "type": "user",
        "deptlevel": "",
        "peak_deptId": "",
        "order_no": "",
        "historyId": "",
        "historycode": "",
        "id": "4028d00e7032610b0170a8f6f079022d",
        "title": "处长三",
        "leaf": true,
        "children": [],
        "selectable": true
      },
      {
        "uuid": "4028d00e6ec42073016ec4728de40046",
        "uupid": "4028d00e6ec42073016ec466150c000e",
        "name": "处长一",
        "treeId": "",
        "superTreeId": "",
        "type": "user",
        "deptlevel": "",
        "peak_deptId": "",
        "order_no": "",
        "historyId": "",
        "historycode": "",
        "id": "4028d00e6ec42073016ec4728de40046",
        "title": "处长一",
        "leaf": true,
        "children": [],
        "selectable": true
      }
    ],
    "selectable": true
  }
]
```

这次应该返回的是办公室下的子部门，不应该包括办公室本身。

**Comment by fulimin123** [comment]
表单用户选择字段，自定义选择“演示部门”，在预览页面，用户人员树空白
![用户，自定义部门](https://user-images.githubusercontent.com/59549153/82308194-06994780-99f4-11ea-875e-6e6528d82ef8.png)
![人员树空白](https://user-images.githubusercontent.com/59549153/82308212-0d27bf00-99f4-11ea-9d88-c038d2bc85e6.png)

**Comment by superstaring** [comment]
已修复
