### ISSUE TITLE
在预览表单时，点击部门选择、用户选择空白区域，不弹出选择部门、用户选择框

### ISSUE THREAD

**Issue by liujinxing** [sinoui/sino-intellisense-form#573]
如下图所示：

![image](https://user-images.githubusercontent.com/1055306/82190210-46dcc500-9923-11ea-911d-8f1016d10e12.png)

点击这两个选择框的非图标部分，不弹出选项弹窗。并且，边框颜色与普通输入框的颜色不一致。

**Comment by liujinxing** [comment]
参考Select。做到与Select的交互类似即可。

**Comment by fulimin123** [comment]
pass
