### ISSUE TITLE
苹果：已办列表只读页面，地址过长时，显示不全

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#574]
![已办列表只读页面](https://user-images.githubusercontent.com/59549153/82193768-73dfa680-9928-11ea-8357-0dd26bf21b68.png)

**Comment by maitian0222** [comment]
地址选择字段的只读视图使用一个多行文本字段显示省市区和详细地址

**Comment by superstaring** [comment]
已修复

**Comment by fulimin123** [comment]
pass
