### ISSUE TITLE
在移动端展现不下超过4个字的按钮标题，应调整按钮标题名称

### ISSUE THREAD

**Issue by liujinxing** [sinoui/sino-intellisense-form#577]
在移动端展现5个字的按钮标题如下图所示：

![image](https://user-images.githubusercontent.com/1055306/82207049-ce363280-993b-11ea-98ae-51de23c00096.png)

1. 将“退回起草人”改成“退起草人”
2. 应考虑手机屏幕宽度，显示按钮个数，最多显示5个，根据屏幕宽度，可以减小为4个，或者3个，总之，保证能够显示4个汉字的标题。
3. 应尽量将标题长的按钮放到更多中显示
4. 通过样式保证，标题不换行显示，超出部分直接隐藏

**Comment by fulimin123** [comment]
谷歌浏览器中问题已解决。
安卓版本，四个字的按钮仍存在换行的问题。

![安卓机](https://user-images.githubusercontent.com/59549153/82416923-699ae500-9aad-11ea-9da5-f6030642aa2d.png)

**Comment by fulimin123** [comment]
pass
