### ISSUE TITLE
授权完数据查看人员发布后，数据查看人员登录系统，没有该表单。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#579]
![数据查看人员登录系统后，没有该表单。](https://user-images.githubusercontent.com/59549153/82275170-a33bf500-99b4-11ea-9f92-7ee3bb05126b.png)
![王一博](https://user-images.githubusercontent.com/59549153/82275194-b058e400-99b4-11ea-8155-01043b5ea3a2.png)

**Comment by wxz0107** [comment]
已解决

**Comment by fulimin123** [comment]
新建表单，设置数据查看人员，发布审核通过后，数据查看人员仍没有该刚刚新建的表单。

**Comment by fulimin123** [comment]
pass
