### ISSUE TITLE
删除草稿时，删除提示错误

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#580]
![删除失败](https://user-images.githubusercontent.com/59549153/82275485-7fc57a00-99b5-11ea-9d18-29a10edeb739.png)

**Comment by wxz0107** [comment]
现在看到的问题是 子表单 没有表名。 发布的时候 不要多次点击

**Comment by liujinxing** [comment]
@maitian0222 解决多次点击发布按钮的问题。
