### ISSUE TITLE
部门或用户单选时，在前面 加个勾选框是不是更合适一些？ 就像多选时的勾选框一样。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#581]
![勾选框](https://user-images.githubusercontent.com/59549153/82275685-f498b400-99b5-11ea-9766-ce37e7ac3395.png)

**Comment by tianyanqiu** [comment]
人员部门选择树单选时按目前交互处理，不再添加选择框。

**Comment by fulimin123** [comment]
目前这种交互，还存在一个问题，就是选择完后取消不了，必须要选择一个回显到字段中。

**Comment by tianyanqiu** [comment]
人员部门树的单选清空暂时不考虑。

**Comment by fulimin123** [comment]
pass
