### ISSUE TITLE
下拉选择字段：选项取消选择后，背景色的灰色建议改为白色；不需要太多颜色，选中了就是蓝色，取消了就是白色。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#585]
![取消后的颜色](https://user-images.githubusercontent.com/59549153/82283421-ec963f80-99c8-11ea-9941-5b17820f8490.png)

**Comment by maitian0222** [comment]
@liujinxing 需要确认是否采纳该建议

**Comment by fulimin123** [comment]
仍是原来的样式

**Comment by superstaring** [comment]
这个是移动端的做了调整，可以在测试一下

**Comment by fulimin123** [comment]
目前存在的问题是，选中后会有深蓝和浅蓝两种颜色；
我的建议是：选中就只显示深蓝色，不要浅蓝色，最后只保留白色和深蓝两种颜色。看看能否实现。

**Comment by superstaring** [comment]
这个问题说以后在考虑
