### ISSUE TITLE
安卓：填充模式，浮动布局时，字段标题与下一行输入的内容距离太近。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#590]
![填充模式-浮动布局](https://user-images.githubusercontent.com/59549153/82303805-072edf80-99ee-11ea-8e55-1687ffac5def.png)

**Comment by maitian0222** [comment]
@fulimin123 表单填报页面默认是密集模式，密集模式下字段标题和字段内容间距会紧凑些。可以在表单设计时，在表单设计的表单属性中，密集模式设置为"否"，非密集模式下间距会大一些。

**Comment by fulimin123** [comment]
非密级模式下间距也没有拉大。

**Comment by liujinxing** [comment]
填充模式输入框的边距确实有一些小问题，在视觉上输入框文本与标签挨得太近，可以将输入框的内边距稍作调整：

* 正常模式下：`padding: 23.5px 12px 8.5px`调整为`padding: 25.5px 12px 6.5px`
* 密集模式下：`padding: 19.5px 12px 4.5px`调整为`padding: 20.5px 12px 3.5px`

**Comment by liujinxing** [comment]
地址栏输入框的`variant`应该与地址栏本身的`variant`保持一致。另外，减小地址栏输入框与选择框之间的间距。

**Comment by liujinxing** [comment]
重新调整@sinoui/rx-core-form的FormItem底部间距：默认为`24px`，有帮助性文本或者错误提示时，调整为`32px`。（需要验证一下实际效果。）

**Comment by fulimin123** [comment]
pass
