### ISSUE TITLE
安卓：边框模式，字段标题与上一行字段描述之间的距离太近；字段标题与下一行输入内容之间的距离也太近。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#591]
![边框模式-浮动布局](https://user-images.githubusercontent.com/59549153/82304310-c08db500-99ee-11ea-9b36-7999634553ea.png)

**Comment by maitian0222** [comment]
当有帮助文本或错误信息时，增大表单项的下边距

**Comment by fulimin123** [comment]
pass
