### ISSUE TITLE
移动端：只读页面，地址选择中省市县过长时，显示不全

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#592]
![显示不全1](https://user-images.githubusercontent.com/59549153/82305385-23cc1700-99f0-11ea-86c1-c2c6967670d6.png)
![显示不全2](https://user-images.githubusercontent.com/59549153/82305429-30e90600-99f0-11ea-8ebc-57292efa0ef7.png)

**Comment by maitian0222** [comment]
重复缺陷 同#574一样
