### ISSUE TITLE
工作流设计器：在表单中可以设计多个流程，根据不同条件走不同的流程

### ISSUE THREAD

**Issue by liujinxing** [sinoui/sino-intellisense-form#597]
## 需求描述：
用户在表单设计时，可以根据实际需求设计多个流程。流程属性设置中增加流程名称、使用范围属性（部门范围用来控制起草发送数据时，使用哪一个流程来流转数据）、流程流转控制公式(属性设置的规范同路由控制公式)的设置和删除流程功能。
### 实现细节：
1. 流程设计器工具栏上增加 `流程列表下拉列表` 和 `新增流程图标按钮`
2. 流程设计器默认显示第一个流程设计的流程图，点击`新增流程`后，流程设计面板显示一个新的默认流程图，同时将流程名称默认为`流程{流程序号}`（从1开始，第一个流程时不需要显示流程序号）
3. 流程设计增加属性设置:`流程名称`，`流程使用范围`和`流程控制公式`，`流程删除按钮`，只有一个流程时，不显示删除流程按钮
4. 点击流程设计器工具栏上`流程列表下拉列表`选项，切换显示对应的流程
5. 发布和保存时，请求参数中的表单设计数据新增flowConfigs字段用来存储多个流程，flowConfigs中每一项的数据格式同原flowConfig的数据结构一致，目前另外补充新增了流程名称(flowName)、使用范围(deptScope)和流程控制公式(controlExpression)字段。
6. 表单应用中，用户起草表单时，后端根据当前用户所在部门和该表单的流程的使用范围做匹配，返回满足使用范围的第一个流程，对应起草页面显示的表单组件和该流程开始节点配置的字段权限保持一致。
7. 点击发送按钮，前端根据起草用户所在部门的信息和流程设计的使用范围、流程控制公式做匹配来决定使用哪一个流程：
   - 若多个流程均未设置使用范围和控制公式，提示用户`没有匹配到可用流程，请先检查流程设计配置`
   - 若流程只设置了控制公式或使用范围，则只需满足控制公式或使用范围的流程均为可发送的流程
   - 若流程同时设置了使用范围和控制公式，则流程必须满足使用范围和控制公式的流程才为可发送的流程
   - 匹配到多个可发送的流程后，使用匹配到的第一个流程
   - 未匹配到可发送的流程后，提示用户`没有匹配到可用流程，请先检查流程设计配置`
8. 获取当前已登录用户信息的接口需要返回用户所在部门及祖先部门的信息（需要后端在用户基本信息接口中增加deptInfo字段）
#### 需要对历史数据做兼容
1. 表单设计详情接口返回表单设计详细数据时，前端需要先判断当前表单设计数据是否存在flowConfigs字段，若没有，手动生成flowConfigs ,将flowConfig作为flowConfigs的第一项，同时将流程名称设置为`流程`
2. 表单应用系统，业务数据详情接口后端在返回详情数据时，formDesign.flowConfig字段需要保留，值为当前业务数据应用的流程配置
3. 表单应用系统，业务详情接口的业务数据formValues字段增加流程id(workflowId)属性
### 列表数据
1. 待办、已办和查询列表显示该表单下和多个流程有关的所有数据

**Comment by wxz0107** [comment]
### 发布表单

1. 多个工作流发布，发布后回写工作流的id，工作流需要新增一个工作流名称，和部门范围
2. 原有的flowConfig 兼容为flowConfigs 字段
3. 资源的集成，需要将原来的单表单流程。遍历出多个以后。再作合并处理。

### 人员信息

1. 后端在用户基本信息接口中增加deptInfo字段，需要返回用户所在部门及祖先部门的信息



### 其他调整

1. 原来flowConfig 都需要改为flowConfigs

**Comment by fulimin123** [comment]
1.40版本的表单直接使用、以及重新编辑发布，再次应用时仍有问题。

**Comment by fulimin123** [comment]
pass
