### ISSUE TITLE
在起草页面或待办中打开具有可编辑子表单功能时，第一个子表单不应该给删除功能的吧？

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#601]
![子表单删除](https://user-images.githubusercontent.com/59549153/82628187-c538b000-9c1e-11ea-8b71-564dab53aa03.png)

**Comment by liujinxing** [comment]
暂不处理。第一个子表单如果填写了数据，应该是允许删除的。所以这个删除功能可以一直存在。

**Comment by fulimin123** [comment]
pass
