### ISSUE TITLE
样式：移动端表单显示下拉滚动条样式不好看

### ISSUE THREAD

**Issue by DragonCloudsBai** [sinoui/sino-intellisense-form#605]
移动端有多个表单项显示滚动条，滚动条与input框右侧重合
![image](https://user-images.githubusercontent.com/11955014/82783862-f371f600-9e91-11ea-8220-990801c351b1.png)

**Comment by liujinxing** [comment]
还会出现横向滚动条。

**Comment by fulimin123** [comment]
手机预览页面仍有横向滚动条。
![横向滚动条](https://user-images.githubusercontent.com/59549153/83097574-ff9cc400-a0da-11ea-8542-985291613b30.png)

**Comment by fulimin123** [comment]
ie中仍存在横向滚动条，可用“5-29”表单查看

**Comment by fulimin123** [comment]
pass
