### ISSUE TITLE
bug:流程发布时获取人员范围错误

### ISSUE THREAD

**Issue by DragonCloudsBai** [sinoui/sino-intellisense-form#609]
在流程设计页面时选择了角色与角色所在部门范围后，发布表单，在接收表单发布的数据接口logProcessSave中获取不到业务角色涉及的部门范围
![image](https://user-images.githubusercontent.com/11955014/82785543-60d35600-9e95-11ea-8de7-418143e73730.png)
![image](https://user-images.githubusercontent.com/11955014/82785679-ad1e9600-9e95-11ea-997f-7d8f2067e41d.png)

**Comment by fulimin123** [comment]
pass
