### ISSUE TITLE
气象局项目：智能表单发布出来的表单添加logo

### ISSUE THREAD

**Issue by DragonCloudsBai** [sinoui/sino-intellisense-form#610]
气象局项目要求使用同一的logo样式，目前发布出来的表单没有logo
![image](https://user-images.githubusercontent.com/11955014/82785866-fec72080-9e95-11ea-9ce0-9fbe2f7f468d.png)
示例：Log是一个固定图片+系统名称
![image](https://user-images.githubusercontent.com/11955014/82785956-2b7b3800-9e96-11ea-839a-6dc1e6e6df1c.png)
![image](https://user-images.githubusercontent.com/11955014/82785999-48b00680-9e96-11ea-8319-46dc35b6537f.png)

**Comment by liujinxing** [comment]
添加logo参数和副标题，这两个都是可选的：

* `logo` - 指定logo的url地址，展现大小为`48px * 48px`。
* `subtitle` - 指定副标题。会在表单标题之上显示。
