### ISSUE TITLE
移动端各个发布的表单不集成在一起

### ISSUE THREAD

**Issue by DragonCloudsBai** [sinoui/sino-intellisense-form#611]
移动端发布的表单希望有自己的home页，不展示其他发布的表单，现在是集成在一个页面上
![image](https://user-images.githubusercontent.com/11955014/82786252-d855b500-9e96-11ea-9fff-34d2b574ad15.png)

**Comment by superstaring** [comment]
点击单个表单，进入单个表单的首页，待办已办草稿操作集成在一个页面

**Comment by fulimin123** [comment]
pass
