### ISSUE TITLE
表单应用：流程设计时，设计的是处长审批送给司长审批，但是发送流程时却是送结束节点

### ISSUE THREAD

**Issue by liujinxing** [sinoui/sino-intellisense-form#613]
流程设计如下：

![image](https://user-images.githubusercontent.com/1055306/82807080-ac97f680-9eb9-11ea-8a01-9ea8a7b4e2de.png)

处长一登录发送流程的实际流程如下：

![image](https://user-images.githubusercontent.com/1055306/82807115-be799980-9eb9-11ea-8c77-e2eb1d9098c4.png)

**Comment by liujinxing** [comment]
经分析，是因为在调整路由时，没有手动修改路由名称导致。调整为，只要路由的结束节点发生了变化，则自动调整路由名称。@maitian0222

**Comment by fulimin123** [comment]
pass
