### ISSUE TITLE
首次发布后，重新调整流程设计，增加节点，修改路由和授权方式，二次发布后，流程中的节点没有该表单。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#627]
首次发布后再次在流程设计中重新设计流程，增加节点、调整授权方式，二次发布。此时起草人发走后，下一节点接收人没有该表单。
![1](https://user-images.githubusercontent.com/59549153/83117379-91b6c380-a0ff-11ea-8a7d-10bd340f5190.png)
使用戴纲登录，发给王甫棣后，王甫棣节点，没有“子表单5-28”

**Comment by fulimin123** [comment]
pass

**Comment by liujinxing** [comment]
@fulimin123 已经验证，汪芳可以发送给审批节点：

![image](https://user-images.githubusercontent.com/1055306/83364475-1ccfdc00-a3d4-11ea-8933-5d73e91eafa4.png)

**Comment by fulimin123** [comment]
pass
