### ISSUE TITLE
谷歌：单行文本，查询条件选择“不等于XXX”时，为空的数据，没有查询出来

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#630]
![a](https://user-images.githubusercontent.com/59549153/83211905-d5a5d900-a190-11ea-8e5b-65d612e2ec35.png)
![b](https://user-images.githubusercontent.com/59549153/83211918-de96aa80-a190-11ea-9bc1-2d15abbafcd6.png)

**Comment by wxz0107** [comment]
数据库自身行为 NULL值 直接过滤掉

**Comment by fulimin123** [comment]
pass
