### ISSUE TITLE
谷歌：部门选择，“包含、等于、不等于”查询结果错误

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#631]
![这三个查询条件查询结果错误！](https://user-images.githubusercontent.com/59549153/83212196-91670880-a191-11ea-9d9f-1008bb217d54.png)

**Comment by wxz0107** [comment]
没有发现问题 。最好把结果集截图发出来

**Comment by liujinxing** [comment]
验证已修复。

**Comment by fulimin123** [comment]
pass
