### ISSUE TITLE
谷歌：复选框组选择“不包含xxx”，为空的数据查询不出来。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#633]
![123](https://user-images.githubusercontent.com/59549153/83213735-7c8c7400-a195-11ea-99fc-88757f7ab35e.png)
![为空数据没查出](https://user-images.githubusercontent.com/59549153/83213746-81e9be80-a195-11ea-897e-63efb8a3b007.png)

**Comment by wxz0107** [comment]
数据库行为  会排除NULL值

**Comment by fulimin123** [comment]
pass
