### ISSUE TITLE
预览移动端样式与真实情况不一致

### ISSUE THREAD

**Issue by DragonCloudsBai** [sinoui/sino-intellisense-form#642]
当选择水平排列时，预览移动端排列方式应为垂直排列，也变成水平排列了
![image](https://user-images.githubusercontent.com/11955014/83834922-0d2cfc00-a722-11ea-9a1a-aaf686e45024.png)
![image](https://user-images.githubusercontent.com/11955014/83834940-17e79100-a722-11ea-9a20-2ea52a25993f.png)

**Comment by liujinxing** [comment]
日期选择、日期区间选择组件需要调整。@tianyanqiu

**Comment by fulimin123** [comment]
手机预览及应用后起草页面仍存在该问题
