### ISSUE TITLE
优化：更精细化的流程控制

### ISSUE THREAD

**Issue by DragonCloudsBai** [sinoui/sino-intellisense-form#643]
![image](https://user-images.githubusercontent.com/11955014/83835037-58470f00-a722-11ea-914a-6b8946169307.png)
单选按钮的其他选项中可以选择人员、日期等数据，发送工作流时，根据选择的人员能直接发送到这个人员这里，不用再去选择发送人

**Comment by liujinxing** [comment]
# 设计

此优化分成两个部分，即：

* 部分1：单选按钮组、复选按钮组的其他选项的输入框类型可以切换
* 部分2：流程节点的负责人可以选择表单中的人员字段

## 原始需求

用印审批流程，在选择用章类型为`人名章`，并选择`张三司长`时，表示该申请是需要使用`张三司长`的人名章，申请如下所示：

![design2](https://user-images.githubusercontent.com/1055306/84618229-27c25a80-af04-11ea-9cc5-d227f915959b.png)


那么审批流程需要经过`张三司长`审批，方可使用该司长人名章：

![design3](https://user-images.githubusercontent.com/1055306/84618233-2b55e180-af04-11ea-9a98-9b109e5f53a9.png)

## 部分1

单选按钮组、复选按钮组的其他选项输入框类型可以在以下几种表单字段中切换：

* 单行文本
* 部门选择
* 用户选择
* ~~日期选择~~

其中部门选择、用户选择字段可以选择部门范围、用户范围。

## 部分2

在流程设计器中，需要新增节点属性`来自表单字段的负责人`，如下所示：

![design](https://user-images.githubusercontent.com/1055306/84618241-2f81ff00-af04-11ea-8592-484fffd78fdb.png)

这个属性是一个下拉框，选项是表单中所有的人员选择字段，包括单选按钮组、复选按钮组中的其他选项以及子表单中的人员选择字段。

下拉框选项的数据：

| 字段类型               | 选项value           | 选项title           | 解析                                                         |
| ---------------------- | ------------------- | ------------------- | ------------------------------------------------------------ |
| 普通的人员选择字段     | 字段名称            | 字段名称            | 用户id：`formValue[字段名称].ids`，<br/>用户名称：`formValue[字段名称].titles` |
| 单选按钮组、复选按钮组 | 字段名称            | 字段名称            | 用户id：`formValue[字段名称].otherText.ids`<br/>用户名称：`formValue[字段名称].otherText.titles` |
| 复选按钮组             | 子表单名称.字段名称 | 子表单名称.字段名称 | 针对`formValue[子表单名称]`循环遍历，按照以上规则。          |

表格中的解析一列，是在流程发送时才需要处理的。

在流程发送时，首先判断下一个环节有几个可选的路由，如果只有一条，则：

> 判断是否有`来自表单字段的负责人`属性设置，有的话，解析此负责人。如果解析出空的用户列表，则将提交请求发送给后端处理（按照之前的逻辑处理）。如果解析出一个用户，则直接将流程发送给该用户。如果是多个用户，则弹出流程用户选择界面进行选择。

如果有多个流程环节，进入选择路由界面，选择完路由后，判断此路由对应的节点是否有`来自表单字段的负责人`属性设置。

> 注意，从表单数据中解析出负责人时，一定要注意空的判断。

> 另外，可以考虑工作流提交的选路由、选人环节，不与工作流引擎交互，自行实现一套。可以考量一下工作量，合适的话，放到1.5.0版本中，否则放到1.6.0版本中。先做好设计。1.6.0版本肯定是需要这么做的。因为有好几个缺陷和特性与此有关，不得不这么做。

**Comment by fulimin123** [comment]
已测试完毕
