### ISSUE TITLE
删除草稿时，弹框被遮挡

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#653]
![弹框被遮挡](https://user-images.githubusercontent.com/59549153/84001484-4de27a80-a999-11ea-9447-6e961d0611ce.png)

**Comment by fulimin123** [comment]
使用谷歌浏览器测试，问题依然存在。

**Comment by liujinxing** [comment]
可以考虑使用Popper来实现。

**Comment by liujinxing** [comment]
@maitian0222 可以考虑使用Popper来实现。

**Comment by fulimin123** [comment]
pass
