### ISSUE TITLE
状态选择“包含和等于”，条件输入“通过或流转中”时，查询结果不准确。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#655]
![状态字段查询不准确](https://user-images.githubusercontent.com/59549153/84005424-b3396a00-a99f-11ea-863f-1ff257f52d4d.png)

**Comment by wxz0107** [comment]
该问题是 searchValue没有更新状态导致 问题主要是出在点击 “办结”按钮。 目前已经解决 。需要新走流程才可以测试 。历史数据无法测试

**Comment by fulimin123** [comment]
和issue #727 有关联，待727解决后一起测试。

**Comment by fulimin123** [comment]
![查询失败的情况](https://user-images.githubusercontent.com/59549153/85966474-7be43900-b9f2-11ea-82b1-bd23432ce93a.png)
