### ISSUE TITLE
待办中盖完章发走后，在已办列表中，公章出现了下移的情况。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#659]
![公章定位位置](https://user-images.githubusercontent.com/59549153/84118059-09bcac00-aa65-11ea-8a9f-941bb2306da8.png)
![已办列表公章下移](https://user-images.githubusercontent.com/59549153/84118075-10e3ba00-aa65-11ea-9fbc-a8f210611b20.png)

**Comment by maitian0222** [comment]
@liujinxing @fulimin123 是因为已办详情中附件上传组件不显示附件删除按钮 导致下方组件上移，其实公章的位置是准确的。
