### ISSUE TITLE
js报错，对象不支持find属性或方法

### ISSUE THREAD

**Issue by DragonCloudsBai** [sinoui/sino-intellisense-form#660]
![image](https://user-images.githubusercontent.com/11955014/84172805-01895e80-aaaf-11ea-962d-b3b7b3110807.png)
IE11如图
![image](https://user-images.githubusercontent.com/11955014/84178229-a6f40080-aab6-11ea-9e68-50c7f40a1e3f.png)
chrome现象如图

测试用户：中科软测试二
该用户拥有起草功能，没有审批功能，有该现象
测试用户：wangfudi
该用户有起草功能并且参与流程流转，没有该现象
流程配置：
![image](https://user-images.githubusercontent.com/11955014/84179565-bc6a2a00-aab8-11ea-858d-de575333b8e5.png)
中科软测试二为信息中心下子部门用户

测试起草人节点加上该子部门后问题消失

**Comment by maitian0222** [comment]
未复现，分析可能是接口没有返回正确的数据结构，前端解析数据出现了异常，前端程序做了增强。
