### ISSUE TITLE
移动端拆分每个表单的首页定制化参数失效

### ISSUE THREAD

**Issue by DragonCloudsBai** [sinoui/sino-intellisense-form#661]
![image](https://user-images.githubusercontent.com/11955014/84174417-2c74b200-aab1-11ea-8d2e-6fe7b6d38576.png)
在拆分出来的首页中loginStrategy参数失去作用,他会跳到登录页面，不需要加showbackbutton就有了退回按钮，点击退回按钮没有按照homeUrl参数规定的跳转指定url

**Comment by liujinxing** [comment]
需要使用`encodeURIComponent()`函数格式化一下参数。

#647

**Comment by liujinxing** [comment]
1. 需要使用`singleFormPageBackUrl`代替`homeUrl`，指定单表单页面的回退链接。(showBackButton和homeUrl两个参数控制的是多表单首页的回退按钮行为）
2. loginStrategy参数确实是有缺陷，已经修复。
