### ISSUE TITLE
表单流程设计：节点负责人所在部门范围不可以选择父部门

### ISSUE THREAD

**Issue by DragonCloudsBai** [sinoui/sino-intellisense-form#664]
![image](https://user-images.githubusercontent.com/11955014/84335449-72bc3500-abc7-11ea-897f-114ed7920ba7.png)
当节点选择信息中心下的处员处长业务角色时，发送提示没有得到下一办理人，选择电子政务处可以选择发送人，电子政务处是信息中心下的部门

**Comment by wxz0107** [comment]
应该是你路由配置信息有问题。看一下路由的配置信息。有一个部门范围  需要配置合理

**Comment by liujinxing** [comment]
@wxz0107 这个是工作流引擎本身就不支持。

@DragonCloudsBai 升级到v1.5.0后，可以在流程设置中添加使用范围，来满足你所描述的场景。
