### ISSUE TITLE
公共问题：预览页面，点击日期选择按钮后，会直接删除当前选择的日期

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#668]
建议：删除功能可以考虑放在在日期控件中

![日期选择按钮](https://user-images.githubusercontent.com/59549153/84610344-d9ee2800-aeec-11ea-8e4b-c450055e501f.png)

**Comment by tianyanqiu** [comment]
日期选择组件设计：日期选择组件有值时，鼠标移入选择区域，最后面的图标会变成"X"号，点击“X”号，清空值。

此问题不属于缺陷。
