### ISSUE TITLE
建议：直接点击“时间选择”文本框时，可弹出时间控件。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#669]
![现象](https://user-images.githubusercontent.com/59549153/84610856-ab714c80-aeee-11ea-84b9-22d3cdddf82e.png)

**Comment by liujinxing** [comment]
只有点击图标才弹出时间选项。点击输入框，是输入框获取到焦点，让用户手动输入时间的。

**Comment by fulimin123** [comment]
厉害！
