### ISSUE TITLE
各浏览器的公共问题：子表单中，日期选择完毕后，不回显。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#671]
![子表单中，日期选择完毕后，不回显。](https://user-images.githubusercontent.com/59549153/84611392-4ae30f00-aef0-11ea-8f98-dbe9a265be54.png)

**Comment by liujinxing** [comment]
与 #672 是同一个问题。

**Comment by fulimin123** [comment]
回测：子表单中日期仍不回显
