### ISSUE TITLE
缺陷：表单字段删除后，流程路由中的流程条件没有自动删除。

### ISSUE THREAD

**Issue by liujinxing** [sinoui/sino-intellisense-form#684]
![image](https://user-images.githubusercontent.com/1055306/84723824-24d57180-afb9-11ea-8dfb-fe27b371920a.png)

子表单中的日期选择字段已经删除：

![image](https://user-images.githubusercontent.com/1055306/84723855-3585e780-afb9-11ea-98a9-c325a535ddf5.png)

**Comment by fulimin123** [comment]
回测：此问题仍存在。
另：按照这样操作，所有可作为流转条件的字段删除后在路由流转条件这里都存在不同步删除的问题。

**Comment by fulimin123** [comment]
pass
