### ISSUE TITLE
一带多流程，发布后，起草人起草后流程发不出去

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#686]
适用“汪芳”登录
![附件1](https://user-images.githubusercontent.com/59549153/84725155-8519e280-afbc-11ea-9c78-21102ff4a776.png)
![附件2](https://user-images.githubusercontent.com/59549153/84725175-9236d180-afbc-11ea-8d08-7a10e2491ef7.png)

**Comment by wxz0107** [comment]
流程部门使用范围 配置问题 。

**Comment by fulimin123** [comment]
pass
