### ISSUE TITLE
一带多流程，汪芳发到戴纲，戴纲点击待办后，报错，数据打不开

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#688]
![查看该数据](https://user-images.githubusercontent.com/59549153/84745316-fcfd0280-afe6-11ea-9504-ec944c9c947d.png)
![1](https://user-images.githubusercontent.com/59549153/84745389-1140ff80-afe7-11ea-9fd2-28a96f740d1f.png)

在已办列表中也出现打开失败的情况，见下图：
![已办列表中数据打开失败](https://user-images.githubusercontent.com/59549153/84750110-74359500-afed-11ea-939b-254438238159.png)

**Comment by wxz0107** [comment]
修复

**Comment by fulimin123** [comment]
一带多流程，除了第一个流程外，其他流程的已办列表，打开数据时都报上面截图中的错误。

**Comment by wxz0107** [comment]
已经修复

**Comment by fulimin123** [comment]
pass
