### ISSUE TITLE
一带多表单，已办列表中，流程日志不显示，流程图点击后，页面展示异常

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#690]
![已办列表中](https://user-images.githubusercontent.com/59549153/84755161-e6a97380-aff3-11ea-8b30-cad15ecb71c9.png)

**Comment by maitian0222** [comment]
@wxz0107 待办、已办详情需要返回flowConfig(当前数据使用的流程设计配置)

**Comment by wxz0107** [comment]
已修复

**Comment by fulimin123** [comment]
一带多流程，第一个流程已办列表所有浏览器都显示正常。其他流程已办列表目前页面不显示。

**Comment by fulimin123** [comment]
pass
