### ISSUE TITLE
起草节点，子表单只勾选部分字段，发布后， 起草人起草页面，子表单及其中所勾选的字段不显示。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#692]
![起草页面子表单字段](https://user-images.githubusercontent.com/59549153/84761450-ffb62280-affb-11ea-90be-8b273342941d.png)
![王帅登录，子表单未显示](https://user-images.githubusercontent.com/59549153/84761569-2d02d080-affc-11ea-9f5b-5c2eb00ca3c2.png)

**Comment by fulimin123** [comment]
问题依然存在

**Comment by fulimin123** [comment]
未解决

**Comment by fulimin123** [comment]
pass

**Comment by fulimin123** [comment]
![Uploading 6-29附件1.png…]()

**Comment by fulimin123** [comment]
问题又重新出现了，见附件
![6-29附件1](https://user-images.githubusercontent.com/59549153/85964027-acc07000-b9ea-11ea-910d-1208e663a980.png)
![6-29附件2](https://user-images.githubusercontent.com/59549153/85964033-b1852400-b9ea-11ea-926e-a4120b07ec63.png)

**Comment by maitian0222** [comment]
@fulimin123 问题重新出现的原因是起草的流程返回不是预期的流程导致的。

**Comment by wxz0107** [comment]
已修复

**Comment by fulimin123** [comment]
pass
