### ISSUE TITLE
删除业务角色所在部门的设置，点击发布，表单发布失败

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#695]
![删除公文处，点击发布](https://user-images.githubusercontent.com/59549153/84867713-35b3df00-b0ae-11ea-86c5-65bd5c4abd54.png)
![修改表单后，表单发布失败](https://user-images.githubusercontent.com/59549153/84867753-406e7400-b0ae-11ea-8b74-d13622dfb736.png)

**Comment by wxz0107** [comment]
新建了一个流程 没有复现出来  把错误例子发一下

**Comment by wxz0107** [comment]
新建没有什么问题 这个流程看了一下 应该是流程发布失败导致流程id重复了
新建流程没有问题。

**Comment by fulimin123** [comment]
pass
