### ISSUE TITLE
谷歌：使用公式控制流程，填报人发送时不满足发送条件，仍能发送出去

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#696]
![流程控制](https://user-images.githubusercontent.com/59549153/84873953-89c2c180-b0b6-11ea-8ec5-635c636bd2ea.png)
![1](https://user-images.githubusercontent.com/59549153/84873977-91826600-b0b6-11ea-9ee1-42d31b4dd695.png)
![2](https://user-images.githubusercontent.com/59549153/84874004-96dfb080-b0b6-11ea-907b-54f5cbb43a11.png)
![3](https://user-images.githubusercontent.com/59549153/84874075-a828bd00-b0b6-11ea-90df-242467aa237c.png)

**Comment by maitian0222** [comment]
表单流程设计只有一个流程时：
1. 没有设置使用范围和控制公式，发送时应用第一个流程
2. 设置了使用范围和控制公式，则进行自动匹配

**Comment by fulimin123** [comment]
一个表单中设计多个流程：
1.如果存在一个设置公式的，其余流程没做任何设置的要怎样处理
2.如果存在一个设置使用范围的，其余流程没做任何设置的要怎样处理
3.如果存在一个流程设置了使用范围，一个流程设置了公式，一个流程什么都没有设置，要怎样处理

**Comment by maitian0222** [comment]
@fulimin123 
如果一个表单设计多个流程，是要求每个流程必须设置使用范围或控制公式，或两者都设置。多个流程的情况，某个流程没有设置使用范围和控制公式的流程认为是配置有误的流程。发送时是匹配不到该流程的。

**Comment by fulimin123** [comment]
pass
