### ISSUE TITLE
 当流转公式选择“单选按钮组”或“复选框组”做控制时，流程发送不出去， 公式控制失败。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#700]
![0](https://user-images.githubusercontent.com/59549153/84991886-affd6580-b179-11ea-8169-e2d09cd8a9de.png)
![1](https://user-images.githubusercontent.com/59549153/84991927-bee41800-b179-11ea-9356-68d5ffb41aee.png)

**Comment by maitian0222** [comment]
@liujinxing 单选按钮组和复现按钮组是只能用in 或 not in 作为公式吗

**Comment by liujinxing** [comment]
是的。等于没有意义。@maitian0222
