### ISSUE TITLE
新建表单，只有默认的一个流程，为设置使用范围和控制公式，发布后，起草人发送不了

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#711]
![一个流程，不设置使用范围和公式](https://user-images.githubusercontent.com/59549153/85129784-4c049b00-b266-11ea-9a30-2ebbea337b8a.png)
![使用汪芳登录，发送不了](https://user-images.githubusercontent.com/59549153/85129814-5a52b700-b266-11ea-9a40-4ac61368c188.png)

**Comment by maitian0222** [comment]
@fulimin123 开始节点配置的负责人是科员，汪芳不属于科员业务角色。不具备起草权限。使用科员登录可以正常起草。

**Comment by fulimin123** [comment]
pass
