### ISSUE TITLE
移动pc交互：同时打开移动端和pc端草稿数据，移动端发走后，pc端草稿数据仍能编辑保存成功，并在草稿列表中生成新的草稿数据。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#725]
现象：1、同时打开移动端和pc端草稿数据，移动端发走后，pc端草稿数据仍能编辑保存成功。
           2、在草稿列表中又生成了一条草稿数据。
预期：如果一端发走后，另一端将不能再保存数据，也不允许生成新的草稿数据。
![移动端问题](https://user-images.githubusercontent.com/59549153/85515025-3d83fe00-b62f-11ea-8a72-dc64f897d01a.png)

**Comment by fulimin123** [comment]
目前经开发处理后，移动端和pc端交互已控制住，问题已解决。给出的提示个人建议再优化一下。

**Comment by fulimin123** [comment]
后端没处理待办列表保存及发送的提示语

**Comment by wxz0107** [comment]
待办双开 流转后 另一端仍然能保存 改动量比较大   建议放到 1.6版本中

**Comment by wxz0107** [comment]
建议新开一个issue  放到 1.6版本中

**Comment by fulimin123** [comment]
已提
