### ISSUE TITLE
重新发布的表单，删除草稿时，提示信息错误

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#731]
使用的表单与 #713相同

![删除草稿时出现的提示不正确](https://user-images.githubusercontent.com/59549153/85971935-18add300-ba01-11ea-965c-d25162b5135d.png)

**Comment by wxz0107** [comment]
这个是由于之前有一个子表单的数据库没有建立 不知道是之前表单就是个问题表单还是怎么的 删除问题子表单 重新建立子表单  就可以了

**Comment by fulimin123** [comment]
pass
