### ISSUE TITLE
火狐：修改表单名称或在子表单中添加字段，点击发布，提示发布失败；IE浏览器也存在该问题。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#735]
![微信图片_20200630180721](https://user-images.githubusercontent.com/59549153/86114081-a5898700-bafc-11ea-8e51-a3da4b44aeac.png)

**Comment by wxz0107** [comment]
已修复

**Comment by fulimin123** [comment]
IE：修改早期的表单，在表单及子表单中添加字段修改节点负责人后，发布。
存在的问题：
1.有节点丢失
2.表单发布失败

**Comment by fulimin123** [comment]
IE：修改早期的表单，在表单及子表单中添加字段修改节点负责人后，发布。存在的问题：
1.有节点丢失
2.表单发布失败

**Comment by fulimin123** [comment]
pass
