### ISSUE TITLE
其他选项字段类型为“部门选择”时，应用后，直接发送给了单选按钮组其他选项中设置的该部门。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#740]
![01](https://user-images.githubusercontent.com/59549153/86200065-54c26e80-bb8e-11ea-85ee-32e8deaa61b5.png)
![02](https://user-images.githubusercontent.com/59549153/86200072-5b50e600-bb8e-11ea-9050-97977fda22a7.png)
![发送金融保险部](https://user-images.githubusercontent.com/59549153/86200078-60ae3080-bb8e-11ea-8edb-f082ade416e1.png)

**Comment by maitian0222** [comment]
@fulimin123 已修复，需要将原来的表单重新发布后测试。

**Comment by fulimin123** [comment]
pass
