### ISSUE TITLE
单选按钮组、复选框组其他项设置了部门范围，应用后，起草页面，这两个字段其他项显示的仍是全部门。预览页面也有该问题。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#741]
![设置了部门范围](https://user-images.githubusercontent.com/59549153/86200897-8a685700-bb90-11ea-8739-9293d4a4e96b.png)
![部门范围设置完毕应用后，显示了全组织架构](https://user-images.githubusercontent.com/59549153/86200947-a9ff7f80-bb90-11ea-87a5-bd20dfaf528f.png)

**Comment by maitian0222** [comment]
已修复

**Comment by fulimin123** [comment]
pass
