### ISSUE TITLE
移动端：部门人员树打开后，已选择的人员不是展开状态。 

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#744]
![1](https://user-images.githubusercontent.com/59549153/86309475-679c7800-bc4e-11ea-9897-1f81c2aea8c5.png)
![2](https://user-images.githubusercontent.com/59549153/86309491-74b96700-bc4e-11ea-80df-c8fec937d5d6.png)
预期：已选择的人员是选中状态，且选中的人员处的列表是展开的；
原因：人员选择较多时，表单页面上是显示不全的，需要点开来看，点开后，如果不直接展开，用户需要一个个部门去点击，这样不人性。

**Comment by maitian0222** [comment]
人员部门树弹出后，单选时也显示已选中项。多选时，PC端在右侧显示已选中项，移动端在上方区域显示已选中项目。

**Comment by fulimin123** [comment]
pass
