### ISSUE TITLE
设置了表单字段负责人，起草完发送时，未发给选择的表单字段负责人，而是弹出了选择处长的选项框。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#749]
![使用汪芳登录，其他项选择戴纲，发送后，](https://user-images.githubusercontent.com/59549153/86338978-9b46c480-bc85-11ea-99d0-895abe7e6edc.png)
![现象](https://user-images.githubusercontent.com/59549153/86339002-a1d53c00-bc85-11ea-9f18-755f41a9d3af.png)

**Comment by maitian0222** [comment]
经分析，表单数据详情接口formDesign中的flowConfig和flowConfigs中对应的流程设计不一致，节点缺少表单负责人字段。导致表单字段负责人获取不到。需要排查下后端接口。

**Comment by wxz0107** [comment]
已修复

**Comment by fulimin123** [comment]
pass
