### ISSUE TITLE
单选按钮组、复选框组的“其他”项设置了字段类型后，在高级查询中，按照单选按钮组、复选框组查询时，查询结果均不正确。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#751]
使用汪芳登录复现
![123](https://user-images.githubusercontent.com/59549153/86425778-9ed75b80-bd18-11ea-831a-c4f9d714ede1.png)

**Comment by maitian0222** [comment]
@fulimin123 单复选，需要按照其他选项查询时，查询值为其他选项的选项名称。是否需要将其他选项的值作为查询值需要再确认。

**Comment by fulimin123** [comment]
pass
