### ISSUE TITLE
高级查询：单选按钮组，按照“其他”查询时，包含、等于、不等于查询结果不正确；按等于查询时查出的是不等于的数据，按不等于查询时查出的是等于的数据。

### ISSUE THREAD

**Issue by fulimin123** [sinoui/sino-intellisense-form#754]
![等于其他的数据](https://user-images.githubusercontent.com/59549153/86428771-283e5c00-bd20-11ea-94ba-92570b335df7.png)

**Comment by wxz0107** [comment]
单选按钮组怎么看复选按钮？而且 我刚才查询 没有发现该问题 重新测试一下 再发一下问题的数据。。。历史数据如果流转或者保存过有参考意义

**Comment by fulimin123** [comment]
pass
